"use client";

import { useMemo, useState } from "react";
import { Building2, ChevronDown, CircleDollarSign, MapPin, MoreHorizontal, Phone, Plus, Search, ShoppingCart, Store, Users, WalletCards, X } from "lucide-react";
import { branches, type Branch, type BranchStatus } from "@/lib/organization-mock-data";

function formatCurrency(value: number) { return new Intl.NumberFormat("en-KE", { style: "currency", currency: "KES", maximumFractionDigits: 0 }).format(value); }

export function BranchesPage() {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("All statuses"); const [selectedId, setSelectedId] = useState("cbd"); const [open, setOpen] = useState(false);
  const selected = branches.find((branch) => branch.id === selectedId) ?? branches[0];
  const filtered = useMemo(() => { const n = query.trim().toLowerCase(); return branches.filter((branch) => (status === "All statuses" || branch.status === status) && (!n || `${branch.name} ${branch.location} ${branch.manager}`.toLowerCase().includes(n))); }, [query, status]);
  const active = branches.filter((branch) => branch.status === "Active").length; const tills = branches.reduce((sum, branch) => sum + branch.tills, 0); const sales = branches.reduce((sum, branch) => sum + branch.salesToday, 0);
  return <div className="mx-auto max-w-[1700px]">
    <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#16A34A]">Business locations</p><h2 className="mt-1 text-2xl font-black text-[#10271B] md:text-3xl">Branches</h2><p className="mt-1 text-sm text-[#789083]">Manage outlets, tills, staff allocation and branch performance.</p></div><button onClick={() => setOpen(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[#16A34A] px-4 py-3 text-xs font-black text-white shadow-lg shadow-[#16A34A]/15"><Plus size={16} />Add branch</button></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={Store} label="Total branches" value={`${branches.length} locations`} note="Across your business" /><Summary icon={Building2} label="Active branches" value={`${active} online`} note="Ready for transactions" /><Summary icon={ShoppingCart} label="Total tills" value={`${tills} tills`} note="Configured checkout points" /><Summary icon={CircleDollarSign} label="Branch sales today" value={formatCurrency(sales)} note="Combined outlet revenue" /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_330px]"><article className="overflow-hidden rounded-2xl border border-[#DDEAE0] bg-white shadow-sm shadow-[#12311F]/5"><div className="flex flex-col gap-3 border-b border-[#E8F0EA] p-4 sm:flex-row"><SearchBox value={query} onChange={setQuery} /><Filter value={status} onChange={setStatus} /></div><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1280px] border-collapse text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-[0.13em] text-[#789083]"><th className="px-4 py-3.5">Branch</th><th className="px-3 py-3.5">Location</th><th className="px-3 py-3.5">Manager</th><th className="px-3 py-3.5">Phone</th><th className="px-3 py-3.5">Tills</th><th className="px-3 py-3.5">Users</th><th className="px-3 py-3.5">Stock value</th><th className="px-3 py-3.5">Sales today</th><th className="px-3 py-3.5">Status</th><th className="px-4 py-3.5 text-right">Actions</th></tr></thead><tbody>{filtered.map((branch) => <BranchRow key={branch.id} branch={branch} selected={selectedId === branch.id} onSelect={() => setSelectedId(branch.id)} />)}</tbody></table></div><div className="grid gap-3 p-3 lg:hidden">{filtered.map((branch) => <BranchCard key={branch.id} branch={branch} selected={selectedId === branch.id} onSelect={() => setSelectedId(branch.id)} />)}</div><footer className="border-t border-[#E8F0EA] p-4 text-xs text-[#789083]">Showing <b className="text-[#173324]">{filtered.length}</b> of <b className="text-[#173324]">{branches.length}</b> branches</footer></article><BranchProfile branch={selected} /></section>
    {open && <AddBranchDialog onClose={() => setOpen(false)} />}
  </div>;
}
function Summary({ icon: Icon, label, value, note }: { icon: typeof Store; label: string; value: string; note: string }) { return <article className="rounded-2xl border border-[#DDEAE0] bg-white p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#16A34A]/10 text-[#16A34A]"><Icon size={18} /></span><p className="mt-4 text-[10px] font-black uppercase tracking-[0.13em] text-[#789083]">{label}</p><p className="mt-1 text-lg font-black text-[#173324]">{value}</p><p className="mt-1 text-[11px] text-[#789083]">{note}</p></article>; }
function SearchBox({ value, onChange }: { value: string; onChange: (v: string) => void }) { return <label className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#789083]" size={16} /><input value={value} onChange={(e) => onChange(e.target.value)} aria-label="Search branches" placeholder="Search branch, location or manager..." className="w-full rounded-xl border border-[#DDEAE0] bg-[#F8FBF8] py-2.5 pl-9 pr-3 text-xs outline-none focus:border-[#16A34A]" /></label>; }
function Filter({ value, onChange }: { value: string; onChange: (v: string) => void }) { return <label className="relative"><select value={value} onChange={(e) => onChange(e.target.value)} aria-label="Filter branch status" className="w-full appearance-none rounded-xl border border-[#DDEAE0] bg-white py-2.5 pl-3 pr-9 text-xs font-bold text-[#60766B] sm:min-w-40"><option>All statuses</option><option>Active</option><option>Inactive</option><option>Maintenance</option></select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#789083]" size={14} /></label>; }
function BranchRow({ branch, selected, onSelect }: { branch: Branch; selected: boolean; onSelect: () => void }) { return <tr onClick={onSelect} className={`cursor-pointer border-t border-[#EEF3EF] text-xs text-[#60766B] hover:bg-[#FBFDFB] ${selected ? "bg-[#16A34A]/[0.035]" : ""}`}><td className="px-4 py-3 font-black text-[#173324]">{branch.name}</td><td className="px-3 py-3">{branch.location}</td><td className="px-3 py-3 font-semibold">{branch.manager}</td><td className="px-3 py-3">{branch.phone}</td><td className="px-3 py-3">{branch.tills}</td><td className="px-3 py-3">{branch.users}</td><td className="px-3 py-3 font-black text-[#173324]">{formatCurrency(branch.stockValue)}</td><td className="px-3 py-3 font-black text-[#0F8C42]">{formatCurrency(branch.salesToday)}</td><td className="px-3 py-3"><Status status={branch.status} /></td><td className="px-4 py-3 text-right"><MoreHorizontal size={16} /></td></tr>; }
function BranchCard({ branch, selected, onSelect }: { branch: Branch; selected: boolean; onSelect: () => void }) { return <button onClick={onSelect} className={`rounded-xl border p-3 text-left ${selected ? "border-[#16A34A]/60 bg-[#16A34A]/[0.035]" : "border-[#E8F0EA]"}`}><div className="flex justify-between gap-2"><div><p className="text-xs font-black text-[#173324]">{branch.name}</p><p className="mt-1 text-[10px] text-[#789083]">{branch.location}</p></div><Status status={branch.status} /></div><div className="mt-3 grid grid-cols-3 rounded-lg bg-[#F8FBF8] p-2.5 text-[10px]"><span><b className="block text-[#789083]">Tills</b><strong>{branch.tills}</strong></span><span><b className="block text-[#789083]">Stock</b><strong>{formatCurrency(branch.stockValue)}</strong></span><span><b className="block text-[#789083]">Sales</b><strong className="text-[#0F8C42]">{formatCurrency(branch.salesToday)}</strong></span></div></button>; }
function Status({ status }: { status: BranchStatus }) { const tone = status === "Active" ? "bg-[#16A34A]/10 text-[#0F8C42]" : status === "Maintenance" ? "bg-[#D4A017]/12 text-[#9A7108]" : "bg-[#789083]/10 text-[#60766B]"; return <span className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-black ${tone}`}>{status}</span>; }
function BranchProfile({ branch }: { branch: Branch }) { return <aside className="overflow-hidden rounded-2xl border border-[#DDEAE0] bg-white xl:sticky xl:top-[96px]"><div className="bg-[#12311F] p-5 text-white"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-white/10 text-sm font-black text-[#22C55E]">{branch.initials}</span><h3 className="mt-4 text-lg font-black">{branch.name}</h3><p className="mt-1 text-[11px] text-[#B8C7BD]">{branch.focus}</p></div><div className="space-y-3 p-4 text-xs text-[#60766B]"><p className="flex gap-2"><MapPin size={14} className="text-[#16A34A]" />{branch.location}</p><p className="flex gap-2"><Phone size={14} className="text-[#16A34A]" />{branch.phone}</p><p className="flex gap-2"><Users size={14} className="text-[#16A34A]" />Manager: {branch.manager}</p></div><div className="grid grid-cols-2 gap-px bg-[#E8F0EA]"><ProfileStat label="Stock value" value={formatCurrency(branch.stockValue)} icon={WalletCards} /><ProfileStat label="Sales today" value={formatCurrency(branch.salesToday)} icon={CircleDollarSign} /></div><div className="p-4"><button className="w-full rounded-xl bg-[#16A34A] py-3 text-xs font-black text-white">View branch overview</button></div></aside>; }
function ProfileStat({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Store }) { return <div className="bg-[#F8FBF8] p-3"><Icon size={14} className="text-[#16A34A]" /><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-[#789083]">{label}</p><p className="mt-1 text-xs font-black text-[#173324]">{value}</p></div>; }
function AddBranchDialog({ onClose }: { onClose: () => void }) { return <div className="fixed inset-0 z-[70] grid place-items-center bg-[#07120D]/65 p-4"><article className="w-full max-w-md rounded-2xl bg-white"><div className="flex items-center justify-between border-b border-[#E8F0EA] p-4"><div><h3 className="text-sm font-black text-[#173324]">Add branch</h3><p className="text-[10px] text-[#789083]">Mock setup form. No branch will be saved.</p></div><button onClick={onClose}><X size={16} /></button></div><div className="grid gap-3 p-4 sm:grid-cols-2">{["Branch name", "Location", "Manager", "Phone", "Number of tills"].map((label) => <label key={label}><span className="text-[10px] font-black uppercase tracking-wider text-[#789083]">{label}</span><input className="mt-2 w-full rounded-xl border border-[#DDEAE0] px-3 py-3 text-xs outline-none focus:border-[#16A34A]" placeholder={`Enter ${label.toLowerCase()}`} /></label>)}<button className="sm:col-span-2 rounded-xl bg-[#16A34A] py-3 text-xs font-black text-white">Save mock branch</button></div></article></div>; }
