import Link from "next/link";
import { PrintButton } from "@/components/print-button";
import { InfoCard, MetricGrid, ProfileHeader, TransactionTable, formatCurrency } from "@/components/profile-ui";
import type { CustomerProfileData } from "@/lib/profile-data";

export function CustomerProfilePage({ customer }: { customer: CustomerProfileData }) {
  return (
    <div className="mx-auto max-w-[1500px]">
      <ProfileHeader
        eyebrow="Customer profile"
        title={customer.name}
        subtitle={`${customer.businessName} - ${customer.type} customer`}
        backHref="/customers"
        backLabel="Back to customers"
        actions={
          <>
            <Link href="/customers" className="rounded-xl border border-[#DDEAE0] bg-white px-4 py-3 text-xs font-black text-[#60766B] hover:bg-[#F8FBF8]">Edit customer</Link>
            <Link href="/debtors" className="rounded-xl bg-[#16A34A] px-4 py-3 text-xs font-black text-white hover:bg-[#12883E]">Record payment</Link>
            <a href="#statement" className="rounded-xl border border-[#D4A017]/40 bg-[#FFF9E8] px-4 py-3 text-xs font-black text-[#8A670C]">View statement</a>
            <PrintButton />
          </>
        }
      />
      <MetricGrid metrics={customer.metrics} />
      <section className="mt-5 grid gap-5 xl:grid-cols-[0.85fr_1.15fr]">
        <InfoCard title="Customer details" rows={[
          ["Phone", customer.phone],
          ["Email", customer.email],
          ["Status", customer.status],
          ["Created", customer.createdAt],
          ["Outstanding debt", formatCurrency(customer.outstandingDebt)],
        ]} />
        <article className="rounded-2xl border border-[#DDEAE0] bg-white p-5">
          <h3 className="text-sm font-black text-[#173324]">Notes</h3>
          <div className="mt-4 space-y-2">
            {customer.notes.map((note) => <p key={note} className="rounded-xl bg-[#F8FBF8] px-4 py-3 text-xs font-bold text-[#60766B]">{note}</p>)}
          </div>
        </article>
      </section>
      <section id="statement" className="mt-5 space-y-5 scroll-mt-24">
        <article className="rounded-2xl border border-[#DDEAE0] bg-white p-5">
          <p className="text-[10px] font-black uppercase tracking-wider text-[#789083]">Printable statement</p>
          <h3 className="mt-1 text-lg font-black text-[#173324]">{customer.name} statement</h3>
          <p className="mt-1 text-xs text-[#789083]">Generated by LeadsStacks POS. Use Print / Save as PDF to produce a customer statement.</p>
          <div className="mt-4 grid gap-3 sm:grid-cols-3">
            <InfoPill label="Total purchases" value={formatCurrency(customer.totalPurchases)} />
            <InfoPill label="Payments made" value={formatCurrency(customer.paymentsMade)} />
            <InfoPill label="Closing balance" value={formatCurrency(customer.outstandingDebt)} danger={customer.outstandingDebt > 0} />
          </div>
        </article>
        <TransactionTable title="Recent sales" empty="No sales recorded for this customer yet." rows={customer.recentSales} />
        <TransactionTable title="Payment history" empty="No payments recorded for this customer yet." rows={customer.payments} />
      </section>
    </div>
  );
}

function InfoPill({ label, value, danger }: { label: string; value: string; danger?: boolean }) {
  return <div className="rounded-xl border border-[#EEF3EF] bg-[#F8FBF8] p-4"><p className="text-[10px] font-black uppercase tracking-wider text-[#789083]">{label}</p><p className={`mt-1 text-sm font-black ${danger ? "text-[#EF4444]" : "text-[#173324]"}`}>{value}</p></div>;
}

