"use client";

import { useState } from "react";
import { ArrowDownLeft, Banknote, ChevronDown, CircleDollarSign, Download, Landmark, MoreHorizontal, Search, Smartphone, TrendingUp, WalletCards } from "lucide-react";
import { bankRecords, expenses, incomeRecords, mpesaRecords, tillSummaries, type ExpenseRecord, type LedgerRecord, type TillSummary } from "@/lib/finance-mock-data";

type Tab = "tills" | "mpesa" | "bank" | "expenses" | "income";
function money(value: number) { return new Intl.NumberFormat("en-KE", { style: "currency", currency: "KES", maximumFractionDigits: 0 }).format(value); }

export function FinancePage() {
  const [tab, setTab] = useState<Tab>("tills"); const [query, setQuery] = useState(""); const [status, setStatus] = useState("All statuses");
  const totalIncome = incomeRecords.reduce((s, i) => s + i.amount, 0); const totalExpenses = expenses.filter((e) => e.status === "Approved").reduce((s, e) => s + e.amount, 0); const cash = tillSummaries.reduce((s, t) => s + t.expectedCash, 0); const mpesa = mpesaRecords.filter((r) => r.status === "Completed").reduce((s, r) => s + r.amount, 0); const bank = bankRecords.filter((r) => r.status === "Completed").reduce((s, r) => s + r.amount, 0);
  return <div className="mx-auto max-w-[1750px]"><div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#16A34A]">Business ledger</p><h2 className="mt-1 text-2xl font-black text-[#10271B] md:text-3xl">Finance & Accounts</h2><p className="mt-1 text-sm text-[#789083]">Track tills, collections, bank activity, expenses and income records.</p></div><button className="flex w-fit items-center gap-2 rounded-xl border border-[#DDEAE0] bg-white px-4 py-3 text-xs font-black text-[#60766B]"><Download size={15} />Download finance report</button></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6"><Summary icon={CircleDollarSign} label="Total income" value={money(totalIncome)} note="Sales and deposits" /><Summary icon={ArrowDownLeft} label="Total expenses" value={money(totalExpenses)} note="Approved business costs" danger /><Summary icon={Banknote} label="Cash balance" value={money(cash)} note="Across open and closed tills" /><Summary icon={Smartphone} label="M-Pesa balance" value={money(mpesa)} note="Completed mobile payments" /><Summary icon={Landmark} label="Bank balance" value={money(bank)} note="Recorded bank activity" /><Summary icon={TrendingUp} label="Profit estimate" value={money(totalIncome - totalExpenses)} note="Income less approved expenses" gold /></section>
    <div className="table-scroll mt-5 flex gap-1 overflow-x-auto rounded-xl border border-[#DDEAE0] bg-white p-1">{([["tills", "Cash drawer / tills"], ["mpesa", "M-Pesa records"], ["bank", "Bank records"], ["expenses", "Expense records"], ["income", "Income records"]] as [Tab, string][]).map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`shrink-0 rounded-lg px-4 py-2.5 text-xs font-black ${tab === id ? "bg-[#12311F] text-white" : "text-[#60766B]"}`}>{label}</button>)}</div>
    <section className="mt-3 overflow-hidden rounded-2xl border border-[#DDEAE0] bg-white shadow-sm shadow-[#12311F]/5"><div className="grid gap-3 border-b border-[#E8F0EA] p-4 sm:grid-cols-[minmax(0,1fr)_180px]"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#789083]" size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} aria-label="Search finance records" placeholder="Search reference, branch or description..." className="w-full rounded-xl border border-[#DDEAE0] bg-[#F8FBF8] py-2.5 pl-9 pr-3 text-xs outline-none" /></label><label className="relative"><select value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Filter finance status" className="w-full appearance-none rounded-xl border border-[#DDEAE0] bg-white py-2.5 pl-3 pr-9 text-xs font-bold text-[#60766B]"><option>All statuses</option><option>Completed</option><option>Pending</option><option>Failed</option><option>Approved</option><option>Rejected</option><option>Open</option><option>Closed</option></select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#789083]" size={14} /></label></div><FinanceTable tab={tab} query={query} status={status} /></section>
  </div>;
}
function Summary({ icon: Icon, label, value, note, danger, gold }: { icon: typeof WalletCards; label: string; value: string; note: string; danger?: boolean; gold?: boolean }) { const tone = danger ? "bg-[#EF4444]/10 text-[#EF4444]" : gold ? "bg-[#D4A017]/12 text-[#A57809]" : "bg-[#16A34A]/10 text-[#16A34A]"; return <article className="rounded-2xl border border-[#DDEAE0] bg-white p-4"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={18} /></span><p className="mt-4 text-[10px] font-black uppercase tracking-wider text-[#789083]">{label}</p><p className={`mt-1 text-lg font-black ${danger ? "text-[#EF4444]" : "text-[#173324]"}`}>{value}</p><p className="mt-1 text-[11px] text-[#789083]">{note}</p></article>; }
function FinanceTable({ tab, query, status }: { tab: Tab; query: string; status: string }) { const n = query.trim().toLowerCase(); if (tab === "tills") return <Tills records={tillSummaries.filter((r) => (status === "All statuses" || r.status === status) && (!n || `${r.till} ${r.branch} ${r.cashier}`.toLowerCase().includes(n)))} />; if (tab === "expenses") return <Expenses records={expenses.filter((r) => (status === "All statuses" || r.status === status) && (!n || `${r.id} ${r.category} ${r.description} ${r.branch}`.toLowerCase().includes(n)))} />; const rows = tab === "mpesa" ? mpesaRecords : tab === "bank" ? bankRecords : incomeRecords; return <Ledger records={rows.filter((r) => (status === "All statuses" || r.status === status) && (!n || `${r.id} ${r.reference} ${r.description} ${r.branch}`.toLowerCase().includes(n)))} />; }
function Tills({ records }: { records: TillSummary[] }) { return <><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-wider text-[#789083]">{["Till", "Branch", "Cashier", "Opening float", "Cash sales", "Cash expenses", "Expected cash", "Status"].map((h) => <th key={h} className="px-4 py-3.5">{h}</th>)}</tr></thead><tbody>{records.map((r) => <tr key={r.id} className="border-t border-[#EEF3EF] text-xs text-[#60766B]"><td className="px-4 py-3 font-black text-[#173324]">{r.till}</td><td className="px-4 py-3">{r.branch}</td><td className="px-4 py-3">{r.cashier}</td><td className="px-4 py-3">{money(r.openingFloat)}</td><td className="px-4 py-3 text-[#0F8C42]">{money(r.cashSales)}</td><td className="px-4 py-3 text-[#EF4444]">{money(r.cashExpenses)}</td><td className="px-4 py-3 font-black text-[#173324]">{money(r.expectedCash)}</td><td className="px-4 py-3"><Badge value={r.status} /></td></tr>)}</tbody></table></div><MobileCards records={records.map((r) => ({ title: r.till, subtitle: `${r.branch} · ${r.cashier}`, amount: money(r.expectedCash), status: r.status }))} /></>; }
function Ledger({ records }: { records: LedgerRecord[] }) { return <><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-wider text-[#789083]">{["Record ID", "Reference", "Description", "Amount", "Branch", "Recorded by", "Date", "Status"].map((h) => <th key={h} className="px-4 py-3.5">{h}</th>)}</tr></thead><tbody>{records.map((r) => <tr key={r.id} className="border-t border-[#EEF3EF] text-xs text-[#60766B]"><td className="px-4 py-3 font-black text-[#173324]">{r.id}</td><td className="px-4 py-3">{r.reference}</td><td className="px-4 py-3">{r.description}</td><td className="px-4 py-3 font-black text-[#173324]">{money(r.amount)}</td><td className="px-4 py-3">{r.branch}</td><td className="px-4 py-3">{r.recordedBy}</td><td className="px-4 py-3">{r.date}</td><td className="px-4 py-3"><Badge value={r.status} /></td></tr>)}</tbody></table></div><MobileCards records={records.map((r) => ({ title: `${r.id} · ${r.reference}`, subtitle: r.description, amount: money(r.amount), status: r.status }))} /></>; }
function Expenses({ records }: { records: ExpenseRecord[] }) { return <><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1180px] text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-wider text-[#789083]">{["Expense ID", "Category", "Description", "Amount", "Payment method", "Branch", "Recorded by", "Date", "Status", "Actions"].map((h) => <th key={h} className="px-4 py-3.5">{h}</th>)}</tr></thead><tbody>{records.map((r) => <tr key={r.id} className="border-t border-[#EEF3EF] text-xs text-[#60766B]"><td className="px-4 py-3 font-black text-[#173324]">{r.id}</td><td className="px-4 py-3">{r.category}</td><td className="px-4 py-3">{r.description}</td><td className="px-4 py-3 font-black text-[#EF4444]">{money(r.amount)}</td><td className="px-4 py-3">{r.paymentMethod}</td><td className="px-4 py-3">{r.branch}</td><td className="px-4 py-3">{r.recordedBy}</td><td className="px-4 py-3">{r.date}</td><td className="px-4 py-3"><Badge value={r.status} /></td><td className="px-4 py-3"><MoreHorizontal size={16} /></td></tr>)}</tbody></table></div><MobileCards records={records.map((r) => ({ title: `${r.id} · ${r.category}`, subtitle: r.description, amount: money(r.amount), status: r.status }))} /></>; }
function MobileCards({ records }: { records: { title: string; subtitle: string; amount: string; status: string }[] }) { return <div className="grid gap-3 p-3 md:hidden">{records.map((r) => <article key={r.title} className="rounded-xl border border-[#E8F0EA] p-3"><div className="flex justify-between gap-2"><div><p className="text-xs font-black text-[#173324]">{r.title}</p><p className="mt-1 text-[10px] text-[#789083]">{r.subtitle}</p></div><Badge value={r.status} /></div><p className="mt-3 text-sm font-black text-[#173324]">{r.amount}</p></article>)}</div>; }
function Badge({ value }: { value: string }) { const danger = ["Failed", "Rejected"].includes(value); const pending = ["Pending", "Open"].includes(value); return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${danger ? "bg-[#EF4444]/10 text-[#EF4444]" : pending ? "bg-[#D4A017]/12 text-[#9A7108]" : "bg-[#16A34A]/10 text-[#0F8C42]"}`}>{value}</span>; }
