"use client";

import { useMemo, useState } from "react";
import { Check, ChevronDown, CircleUserRound, Crown, MoreHorizontal, Plus, Search, ShieldCheck, UserRoundCheck, Users, X } from "lucide-react";
import { branches, permissions, roles, staffUsers, type StaffStatus, type StaffUser } from "@/lib/organization-mock-data";

export function HrmPage() {
  const [tab, setTab] = useState<"staff" | "roles">("staff"); const [query, setQuery] = useState(""); const [role, setRole] = useState("All roles"); const [branch, setBranch] = useState("All branches"); const [open, setOpen] = useState(false);
  const filtered = useMemo(() => { const n = query.trim().toLowerCase(); return staffUsers.filter((user) => (role === "All roles" || user.role === role) && (branch === "All branches" || user.branch === branch) && (!n || `${user.name} ${user.email} ${user.phone}`.toLowerCase().includes(n))); }, [query, role, branch]);
  return <div className="mx-auto max-w-[1700px]"><div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#16A34A]">People and access</p><h2 className="mt-1 text-2xl font-black text-[#10271B] md:text-3xl">HRM</h2><p className="mt-1 text-sm text-[#789083]">Manage staff accounts, assigned tills and role permissions.</p></div><button onClick={() => setOpen(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[#16A34A] px-4 py-3 text-xs font-black text-white"><Plus size={16} />Add user</button></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={Users} label="Total staff" value={`${staffUsers.length} users`} note="Configured employee accounts" /><Summary icon={UserRoundCheck} label="Active users" value={`${staffUsers.filter((u) => u.status === "Active").length} online`} note="Enabled for business access" /><Summary icon={CircleUserRound} label="Cashiers" value={`${staffUsers.filter((u) => u.role === "Cashier").length} cashier`} note="Assigned checkout operators" /><Summary icon={Crown} label="Managers" value={`${staffUsers.filter((u) => u.role === "Branch Manager").length} manager`} note="Branch-level oversight" /></section>
    <div className="mt-5 flex w-fit gap-1 rounded-xl border border-[#DDEAE0] bg-white p-1"><button onClick={() => setTab("staff")} className={`rounded-lg px-4 py-2.5 text-xs font-black ${tab === "staff" ? "bg-[#12311F] text-white" : "text-[#60766B]"}`}>Staff users</button><button onClick={() => setTab("roles")} className={`rounded-lg px-4 py-2.5 text-xs font-black ${tab === "roles" ? "bg-[#12311F] text-white" : "text-[#60766B]"}`}>Roles & permissions</button></div>
    {tab === "staff" ? <StaffRegister query={query} setQuery={setQuery} role={role} setRole={setRole} branch={branch} setBranch={setBranch} users={filtered} /> : <RolesMatrix />}
    {open && <AddUserDialog onClose={() => setOpen(false)} />}
  </div>;
}
function Summary({ icon: Icon, label, value, note }: { icon: typeof Users; label: string; value: string; note: string }) { return <article className="rounded-2xl border border-[#DDEAE0] bg-white p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#16A34A]/10 text-[#16A34A]"><Icon size={18} /></span><p className="mt-4 text-[10px] font-black uppercase tracking-[0.13em] text-[#789083]">{label}</p><p className="mt-1 text-lg font-black text-[#173324]">{value}</p><p className="mt-1 text-[11px] text-[#789083]">{note}</p></article>; }
function StaffRegister({ query, setQuery, role, setRole, branch, setBranch, users }: { query: string; setQuery: (v: string) => void; role: string; setRole: (v: string) => void; branch: string; setBranch: (v: string) => void; users: StaffUser[] }) { return <section className="mt-3 overflow-hidden rounded-2xl border border-[#DDEAE0] bg-white"><div className="grid gap-3 border-b border-[#E8F0EA] p-4 lg:grid-cols-[minmax(0,1fr)_180px_210px]"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#789083]" size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} aria-label="Search staff" placeholder="Search staff, email or phone..." className="w-full rounded-xl border border-[#DDEAE0] bg-[#F8FBF8] py-2.5 pl-9 pr-3 text-xs outline-none" /></label><Select label="Filter staff role" value={role} onChange={setRole} options={["All roles", ...roles.map((item) => item.name)]} /><Select label="Filter staff branch" value={branch} onChange={setBranch} options={["All branches", ...branches.map((item) => item.name)]} /></div><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1240px] text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-[0.13em] text-[#789083]"><th className="px-4 py-3.5">Staff</th><th className="px-3 py-3.5">Email</th><th className="px-3 py-3.5">Phone</th><th className="px-3 py-3.5">Role</th><th className="px-3 py-3.5">Assigned branch</th><th className="px-3 py-3.5">Assigned till</th><th className="px-3 py-3.5">Last login</th><th className="px-3 py-3.5">Status</th><th className="px-4 py-3.5 text-right">Actions</th></tr></thead><tbody>{users.map((user) => <StaffRow key={user.id} user={user} />)}</tbody></table></div><div className="grid gap-3 p-3 lg:hidden">{users.map((user) => <StaffCard key={user.id} user={user} />)}</div><footer className="border-t border-[#E8F0EA] p-4 text-xs text-[#789083]">Showing <b>{users.length}</b> of <b>{staffUsers.length}</b> staff users</footer></section>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: string[] }) { return <label className="relative"><select value={value} onChange={(e) => onChange(e.target.value)} aria-label={label} className="w-full appearance-none rounded-xl border border-[#DDEAE0] bg-white py-2.5 pl-3 pr-9 text-xs font-bold text-[#60766B]">{options.map((o) => <option key={o}>{o}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#789083]" size={14} /></label>; }
function StaffRow({ user }: { user: StaffUser }) { return <tr className="border-t border-[#EEF3EF] text-xs text-[#60766B] hover:bg-[#FBFDFB]"><td className="px-4 py-3"><div className="flex items-center gap-2.5"><Avatar user={user} /><b className="text-[#173324]">{user.name}</b></div></td><td className="px-3 py-3">{user.email}</td><td className="px-3 py-3">{user.phone}</td><td className="px-3 py-3"><RoleBadge role={user.role} /></td><td className="px-3 py-3">{user.branch}</td><td className="px-3 py-3">{user.till}</td><td className="px-3 py-3">{user.lastLogin}</td><td className="px-3 py-3"><Status status={user.status} /></td><td className="px-4 py-3 text-right"><MoreHorizontal size={16} /></td></tr>; }
function StaffCard({ user }: { user: StaffUser }) { return <article className="rounded-xl border border-[#E8F0EA] p-3"><div className="flex gap-3"><Avatar user={user} /><div className="min-w-0 flex-1"><p className="text-xs font-black text-[#173324]">{user.name}</p><p className="truncate text-[10px] text-[#789083]">{user.email}</p></div><Status status={user.status} /></div><div className="mt-3 rounded-lg bg-[#F8FBF8] p-2.5 text-[10px]"><p><RoleBadge role={user.role} /> <span className="ml-2 text-[#789083]">{user.branch}</span></p><p className="mt-2 text-[#789083]">{user.till} · Last login {user.lastLogin}</p></div></article>; }
function Avatar({ user }: { user: StaffUser }) { return <span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#12311F] text-[10px] font-black text-white">{user.initials}</span>; }
function RoleBadge({ role }: { role: string }) { return <span className="rounded-full bg-[#D4A017]/12 px-2.5 py-1 text-[10px] font-black text-[#9A7108]">{role}</span>; }
function Status({ status }: { status: StaffStatus }) { const tone = status === "Active" ? "bg-[#16A34A]/10 text-[#0F8C42]" : status === "Suspended" ? "bg-[#EF4444]/10 text-[#EF4444]" : "bg-[#789083]/10 text-[#60766B]"; return <span className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-black ${tone}`}>{status}</span>; }
function RolesMatrix() { return <section className="mt-3 overflow-hidden rounded-2xl border border-[#DDEAE0] bg-white"><div className="flex items-center gap-3 border-b border-[#E8F0EA] p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#16A34A]/10 text-[#16A34A]"><ShieldCheck size={18} /></span><div><h3 className="font-black text-[#173324]">User roles & permissions</h3><p className="text-xs text-[#789083]">Default access templates for your POS team.</p></div></div><div className="table-scroll overflow-x-auto"><table className="min-w-[1780px] text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-wider text-[#789083]"><th className="sticky left-0 z-10 min-w-56 bg-[#F8FBF8] px-4 py-3.5">Role</th>{permissions.map((p) => <th key={p} className="min-w-28 px-2 py-3.5 text-center">{p}</th>)}</tr></thead><tbody>{roles.map((role) => <tr key={role.name} className="border-t border-[#EEF3EF]"><td className="sticky left-0 bg-white px-4 py-3"><p className="text-xs font-black text-[#173324]">{role.name}</p><p className="mt-0.5 text-[10px] text-[#789083]">{role.users} user · {role.description}</p></td>{permissions.map((permission) => <td key={permission} className="px-2 py-3 text-center">{role.permissions.includes(permission) ? <span className="mx-auto grid h-6 w-6 place-items-center rounded-full bg-[#16A34A]/10 text-[#16A34A]"><Check size={13} /></span> : <span className="text-[#CBD8CF]">—</span>}</td>)}</tr>)}</tbody></table></div></section>; }
function AddUserDialog({ onClose }: { onClose: () => void }) { return <div className="fixed inset-0 z-[70] grid place-items-center bg-[#07120D]/65 p-4"><article className="w-full max-w-md rounded-2xl bg-white"><div className="flex justify-between border-b border-[#E8F0EA] p-4"><div><h3 className="text-sm font-black text-[#173324]">Add staff user</h3><p className="text-[10px] text-[#789083]">Mock form. No account will be created.</p></div><button onClick={onClose}><X size={16} /></button></div><div className="grid gap-3 p-4 sm:grid-cols-2">{["Staff name", "Email", "Phone", "Assigned till"].map((label) => <label key={label}><span className="text-[10px] font-black uppercase tracking-wider text-[#789083]">{label}</span><input className="mt-2 w-full rounded-xl border border-[#DDEAE0] px-3 py-3 text-xs" placeholder={`Enter ${label.toLowerCase()}`} /></label>)}<Select label="Select role" value="Cashier" onChange={() => undefined} options={roles.map((r) => r.name)} /><Select label="Select branch" value="Main Branch" onChange={() => undefined} options={branches.map((b) => b.name)} /><button className="sm:col-span-2 rounded-xl bg-[#16A34A] py-3 text-xs font-black text-white">Save mock user</button></div></article></div>; }
