"use client";

import { useMemo, useState } from "react";
import { ChevronDown, Download, FileText, HandCoins, MoreHorizontal, Search, Truck, Users, WalletCards } from "lucide-react";
import { partyReportCategories, partyReports, type PartyReport } from "@/lib/report-mock-data";
import { exportReportToPdf, exportToCsv } from "@/lib/export";

function money(value: number) { return new Intl.NumberFormat("en-KE", { style: "currency", currency: "KES", maximumFractionDigits: 0 }).format(value); }
export function PartyReportsPage() {
  const [query, setQuery] = useState(""); const [type, setType] = useState("All parties"); const [status, setStatus] = useState("All statuses"); const [feedback, setFeedback] = useState("");
  const filtered = useMemo(() => { const n = query.trim().toLowerCase(); return partyReports.filter((p) => (type === "All parties" || p.type === type) && (status === "All statuses" || p.status === status) && (!n || `${p.name} ${p.phone}`.toLowerCase().includes(n))); }, [query, type, status]);
  const customerBalance = partyReports.filter((p) => p.type === "Customer").reduce((s, p) => s + p.balance, 0); const supplierBalance = partyReports.filter((p) => p.type === "Supplier").reduce((s, p) => s + p.balance, 0); const overdueCustomers = partyReports.filter((p) => p.type === "Customer" && p.status === "Overdue").length; const supplierPending = partyReports.filter((p) => p.type === "Supplier" && p.balance > 0).length;
  const exportRows = filtered.map((party) => ({ "Party name": party.name, "Party type": party.type, Phone: party.phone, "Total transactions": party.transactions, "Total amount": party.totalAmount, "Paid amount": party.paidAmount, Balance: party.balance, "Last transaction": party.lastTransaction, Status: party.status }));
  function exported(message: string) { setFeedback(message); window.setTimeout(() => setFeedback(""), 2500); }
  function downloadPdf() { exportReportToPdf({ filename: "biashara-party-report", title: "Party Reports", summary: { "Customer balances": money(customerBalance), "Supplier balances": money(supplierBalance), "Overdue customers": overdueCustomers }, rows: exportRows }); exported("PDF statement downloaded."); }
  function downloadCsv() { exported(exportToCsv("biashara-party-report", exportRows) ? "CSV statement downloaded." : "No rows to export."); }
  return <div className="mx-auto max-w-[1700px]"><div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#16A34A]">Statements and balances</p><h2 className="mt-1 text-2xl font-black text-[#10271B] md:text-3xl">Party Reports</h2><p className="mt-1 text-sm text-[#789083]">Review customer and supplier transactions, statements and balances.</p></div><div><div className="flex flex-wrap gap-2"><button onClick={downloadPdf} className="flex w-fit items-center gap-2 rounded-xl border border-[#DDEAE0] bg-white px-4 py-3 text-xs font-black text-[#60766B]"><Download size={15} />Download PDF</button><button onClick={downloadCsv} className="flex w-fit items-center gap-2 rounded-xl bg-[#16A34A] px-4 py-3 text-xs font-black text-white"><Download size={15} />Export CSV</button></div>{feedback && <p className="mt-2 text-right text-[11px] font-bold text-[#16A34A]">{feedback}</p>}</div></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={Users} label="Total customer balances" value={money(customerBalance)} note="Outstanding customer debt" danger /><Summary icon={Truck} label="Total supplier balances" value={money(supplierBalance)} note="Payable supplier accounts" gold /><Summary icon={HandCoins} label="Overdue customers" value={`${overdueCustomers} accounts`} note="Requires collection follow-up" danger /><Summary icon={WalletCards} label="Supplier pending payments" value={`${supplierPending} suppliers`} note="Outstanding vendor payments" gold /></section>
    <section className="mt-5"><h3 className="font-black text-[#173324]">Party report categories</h3><p className="text-xs text-[#789083]">Generate a focused party statement or transaction history.</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{partyReportCategories.map((title) => <article key={title} className="flex items-center gap-3 rounded-xl border border-[#DDEAE0] bg-white p-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#16A34A]/10 text-[#16A34A]"><FileText size={15} /></span><div className="flex-1"><p className="text-xs font-black text-[#173324]">{title}</p><button className="mt-1 text-[10px] font-black text-[#16A34A]">Open report</button></div></article>)}</div></section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-[#DDEAE0] bg-white"><div className="grid gap-3 border-b border-[#E8F0EA] p-4 lg:grid-cols-[minmax(0,1fr)_160px_160px]"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#789083]" size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} aria-label="Search parties" placeholder="Search customer, supplier or phone..." className="w-full rounded-xl border border-[#DDEAE0] bg-[#F8FBF8] py-2.5 pl-9 pr-3 text-xs outline-none" /></label><Select label="Party type filter" value={type} onChange={setType} options={["All parties", "Customer", "Supplier"]} /><Select label="Party status filter" value={status} onChange={setStatus} options={["All statuses", "Clear", "Owes", "Overdue"]} /></div><PartyTable records={filtered} /></section>
  </div>;
}
function Summary({ icon: Icon, label, value, note, danger, gold }: { icon: typeof Users; label: string; value: string; note: string; danger?: boolean; gold?: boolean }) { const tone = danger ? "bg-[#EF4444]/10 text-[#EF4444]" : gold ? "bg-[#D4A017]/12 text-[#A57809]" : "bg-[#16A34A]/10 text-[#16A34A]"; return <article className="rounded-2xl border border-[#DDEAE0] bg-white p-4"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={18} /></span><p className="mt-4 text-[10px] font-black uppercase tracking-wider text-[#789083]">{label}</p><p className={`mt-1 text-lg font-black ${danger ? "text-[#EF4444]" : "text-[#173324]"}`}>{value}</p><p className="mt-1 text-[11px] text-[#789083]">{note}</p></article>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: string[] }) { return <label className="relative"><select aria-label={label} value={value} onChange={(e) => onChange(e.target.value)} className="w-full appearance-none rounded-xl border border-[#DDEAE0] bg-white py-2.5 pl-3 pr-9 text-xs font-bold text-[#60766B]">{options.map((o) => <option key={o}>{o}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#789083]" size={14} /></label>; }
function PartyTable({ records }: { records: PartyReport[] }) { return <><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1180px] text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-wider text-[#789083]">{["Party name", "Party type", "Phone", "Total transactions", "Total amount", "Paid amount", "Balance", "Last transaction", "Status", "Actions"].map((h) => <th key={h} className="px-4 py-3.5">{h}</th>)}</tr></thead><tbody>{records.map((p) => <tr key={p.id} className="border-t border-[#EEF3EF] text-xs text-[#60766B]"><td className="px-4 py-3 font-black text-[#173324]">{p.name}</td><td className="px-4 py-3"><PartyType value={p.type} /></td><td className="px-4 py-3">{p.phone}</td><td className="px-4 py-3">{p.transactions}</td><td className="px-4 py-3 font-black text-[#173324]">{money(p.totalAmount)}</td><td className="px-4 py-3 text-[#0F8C42]">{money(p.paidAmount)}</td><td className="px-4 py-3 font-black text-[#EF4444]">{money(p.balance)}</td><td className="px-4 py-3">{p.lastTransaction}</td><td className="px-4 py-3"><Status value={p.status} /></td><td className="px-4 py-3"><MoreHorizontal size={16} /></td></tr>)}</tbody></table></div><div className="grid gap-3 p-3 lg:hidden">{records.map((p) => <article key={p.id} className="rounded-xl border border-[#E8F0EA] p-3"><div className="flex justify-between"><div><p className="text-xs font-black text-[#173324]">{p.name}</p><p className="mt-1 text-[10px] text-[#789083]">{p.phone} · {p.type}</p></div><Status value={p.status} /></div><div className="mt-3 grid grid-cols-3 rounded-lg bg-[#F8FBF8] p-2.5 text-[10px]"><span><b className="block text-[#789083]">Total</b><strong>{money(p.totalAmount)}</strong></span><span><b className="block text-[#789083]">Paid</b><strong className="text-[#0F8C42]">{money(p.paidAmount)}</strong></span><span><b className="block text-[#789083]">Balance</b><strong className="text-[#EF4444]">{money(p.balance)}</strong></span></div></article>)}</div></>; }
function PartyType({ value }: { value: "Customer" | "Supplier" }) { return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${value === "Customer" ? "bg-[#16A34A]/10 text-[#0F8C42]" : "bg-[#D4A017]/12 text-[#9A7108]"}`}>{value}</span>; }
function Status({ value }: { value: string }) { return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${value === "Clear" ? "bg-[#16A34A]/10 text-[#0F8C42]" : value === "Overdue" ? "bg-[#EF4444]/10 text-[#EF4444]" : "bg-[#D4A017]/12 text-[#9A7108]"}`}>{value}</span>; }
