"use client";

import { useState } from "react";
import { Banknote, Building2, CreditCard, MoreHorizontal, Plus, Smartphone, Users, WalletCards, X } from "lucide-react";
import { paymentTypes, type PaymentType, type PaymentTypeStatus } from "@/lib/finance-mock-data";

function money(value: number) { return new Intl.NumberFormat("en-KE", { style: "currency", currency: "KES", maximumFractionDigits: 0 }).format(value); }
const icons = { cash: Banknote, mpesa: Smartphone, bank: Building2, card: CreditCard, credit: Users };

export function PaymentTypesPage() {
  const [open, setOpen] = useState<PaymentType | "add" | null>(null);
  return <div className="mx-auto max-w-[1500px]"><div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#16A34A]">Checkout configuration</p><h2 className="mt-1 text-2xl font-black text-[#10271B] md:text-3xl">Payment Types</h2><p className="mt-1 text-sm text-[#789083]">Configure the methods available during POS checkout.</p></div><button onClick={() => setOpen("add")} className="flex w-fit items-center gap-2 rounded-xl bg-[#16A34A] px-4 py-3 text-xs font-black text-white"><Plus size={16} />Add payment type</button></div>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{paymentTypes.map((item) => <PaymentCard key={item.id} item={item} onEdit={() => setOpen(item)} />)}</section>
    {open && <PaymentDialog item={open} onClose={() => setOpen(null)} />}
  </div>;
}
function PaymentCard({ item, onEdit }: { item: PaymentType; onEdit: () => void }) { const Icon = icons[item.id as keyof typeof icons] ?? WalletCards; return <article className="rounded-2xl border border-[#DDEAE0] bg-white p-5 shadow-sm shadow-[#12311F]/5"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#16A34A]/10 text-[#16A34A]"><Icon size={21} /></span><button onClick={onEdit} aria-label={`Edit ${item.name}`} className="text-[#789083]"><MoreHorizontal size={18} /></button></div><div className="mt-5 flex items-center gap-2"><h3 className="font-black text-[#173324]">{item.name}</h3><Status value={item.status} /></div><p className="mt-2 text-xs leading-5 text-[#789083]">{item.description}</p><div className="mt-4 grid grid-cols-2 gap-px overflow-hidden rounded-xl bg-[#E8F0EA]"><div className="bg-[#F8FBF8] p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-[#789083]">Transactions</p><p className="mt-1 text-sm font-black text-[#173324]">{item.transactions}</p></div><div className="bg-[#F8FBF8] p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-[#789083]">Total collected</p><p className="mt-1 text-sm font-black text-[#173324]">{money(item.totalCollected)}</p></div></div><button onClick={onEdit} className="mt-4 w-full rounded-xl border border-[#DDEAE0] py-2.5 text-xs font-black text-[#60766B]">Edit / disable payment type</button></article>; }
function Status({ value }: { value: PaymentTypeStatus }) { return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${value === "Active" ? "bg-[#16A34A]/10 text-[#0F8C42]" : "bg-[#789083]/10 text-[#60766B]"}`}>{value}</span>; }
function PaymentDialog({ item, onClose }: { item: PaymentType | "add"; onClose: () => void }) { return <div className="fixed inset-0 z-[70] grid place-items-center bg-[#07120D]/65 p-4"><article className="w-full max-w-md rounded-2xl bg-white"><div className="flex justify-between border-b border-[#E8F0EA] p-4"><div><h3 className="text-sm font-black text-[#173324]">{item === "add" ? "Add payment type" : `Edit ${item.name}`}</h3><p className="text-[10px] text-[#789083]">Placeholder configuration only.</p></div><button onClick={onClose}><X size={16} /></button></div><div className="grid gap-3 p-4"><label><span className="text-[10px] font-black uppercase tracking-wider text-[#789083]">Payment name</span><input defaultValue={item === "add" ? "" : item.name} className="mt-2 w-full rounded-xl border border-[#DDEAE0] px-3 py-3 text-xs outline-none" placeholder="Enter payment method" /></label><label className="flex items-center justify-between rounded-xl border border-[#DDEAE0] p-3 text-xs font-bold text-[#60766B]"><span>Enable at checkout</span><input type="checkbox" defaultChecked={item === "add" || item.status === "Active"} /></label><button className="rounded-xl bg-[#16A34A] py-3 text-xs font-black text-white">Save mock settings</button></div></article></div>; }
