"use client";

import { useMemo, useState } from "react";
import { Boxes, ChartNoAxesCombined, ChevronDown, CircleDollarSign, FileSpreadsheet, FileText, HandCoins, MoreHorizontal, ReceiptText, Search, TrendingUp, WalletCards } from "lucide-react";
import { branches, staffUsers } from "@/lib/organization-mock-data";
import { expenses } from "@/lib/finance-mock-data";
import { warehouses } from "@/lib/inventory-mock-data";
import { reportCategories, reportPreviews, type ReportPreview } from "@/lib/report-mock-data";
import { exportReportToPdf, exportToCsv } from "@/lib/export";

function money(value: number) { return new Intl.NumberFormat("en-KE", { style: "currency", currency: "KES", maximumFractionDigits: 0 }).format(value); }
export function ReportsPage() {
  const [date, setDate] = useState("Today"); const [branch, setBranch] = useState("All branches"); const [user, setUser] = useState("All users"); const [query, setQuery] = useState(""); const [feedback, setFeedback] = useState("");
  const filtered = useMemo(() => { const n = query.trim().toLowerCase(); return reportPreviews.filter((r) => (branch === "All branches" || r.branch === branch) && (user === "All users" || r.createdBy === user) && (!n || `${r.id} ${r.type} ${r.branch} ${r.createdBy}`.toLowerCase().includes(n))); }, [query, branch, user]);
  const stock = warehouses.reduce((s, w) => s + w.stockValue, 0); const expenseTotal = expenses.filter((e) => e.status === "Approved").reduce((s, e) => s + e.amount, 0);
  const exportRows = filtered.map((record) => ({ Date: record.date, "Report type": record.type, Branch: record.branch, "Total sales": record.totalSales, Expenses: record.expenses, "Profit estimate": record.profitEstimate, "Created by": record.createdBy, Status: record.status }));
  function exported(message: string) { setFeedback(message); window.setTimeout(() => setFeedback(""), 2500); }
  function downloadPdf() { exportReportToPdf({ filename: "biashara-sales-report", title: "Reports Preview", summary: { "Today sales": money(184250), "Monthly sales": money(3246800), "Stock value": money(stock), "Total expenses": money(expenseTotal) }, rows: exportRows }); exported("PDF report downloaded."); }
  function downloadCsv() { exported(exportToCsv("biashara-sales-report", exportRows) ? "CSV report downloaded." : "No rows to export."); }
  return <div className="mx-auto max-w-[1750px]"><div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#16A34A]">Business intelligence</p><h2 className="mt-1 text-2xl font-black text-[#10271B] md:text-3xl">Reports</h2><p className="mt-1 text-sm text-[#789083]">Generate operational reports across sales, stock, finance and branches.</p></div><div><div className="flex flex-wrap gap-2"><button onClick={downloadPdf} className="flex items-center gap-2 rounded-xl border border-[#DDEAE0] bg-white px-3.5 py-3 text-xs font-black text-[#60766B]"><FileText size={15} />Download PDF</button><button onClick={downloadCsv} className="flex items-center gap-2 rounded-xl bg-[#16A34A] px-3.5 py-3 text-xs font-black text-white"><FileSpreadsheet size={15} />Export CSV</button></div>{feedback && <p className="mt-2 text-right text-[11px] font-bold text-[#16A34A]">{feedback}</p>}</div></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6"><Summary icon={CircleDollarSign} label="Today sales" value={money(184250)} note="Current business day" /><Summary icon={TrendingUp} label="Monthly sales" value={money(3246800)} note="June performance estimate" /><Summary icon={ChartNoAxesCombined} label="Gross profit estimate" value={money(986400)} note="Estimated margin" gold /><Summary icon={Boxes} label="Stock value" value={money(stock)} note="All warehouses combined" /><Summary icon={WalletCards} label="Total expenses" value={money(expenseTotal)} note="Approved expense records" danger /><Summary icon={HandCoins} label="Total debtors" value={money(161900)} note="Outstanding customer balances" danger /></section>
    <section className="mt-5"><div className="mb-3 flex items-end justify-between"><div><h3 className="font-black text-[#173324]">Report categories</h3><p className="text-xs text-[#789083]">Choose a report template to generate a preview.</p></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{reportCategories.map((item) => <article key={item.title} className="rounded-xl border border-[#DDEAE0] bg-white p-4 hover:border-[#16A34A]/50"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#16A34A]/10 text-[#16A34A]"><ReceiptText size={16} /></span><h4 className="mt-3 text-xs font-black text-[#173324]">{item.title}</h4><p className="mt-1 text-[11px] leading-5 text-[#789083]">{item.description}</p><button className="mt-3 text-[10px] font-black text-[#16A34A]">Generate report</button></article>)}</div></section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-[#DDEAE0] bg-white"><div className="grid gap-3 border-b border-[#E8F0EA] p-4 lg:grid-cols-[minmax(0,1fr)_160px_190px_180px]"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#789083]" size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} aria-label="Search report previews" placeholder="Search report preview..." className="w-full rounded-xl border border-[#DDEAE0] bg-[#F8FBF8] py-2.5 pl-9 pr-3 text-xs outline-none" /></label><Select label="Date filter" value={date} onChange={setDate} options={["Today", "This week", "This month", "Custom date range"]} /><Select label="Branch filter" value={branch} onChange={setBranch} options={["All branches", ...branches.map((b) => b.name)]} /><Select label="Cashier filter" value={user} onChange={setUser} options={["All users", ...staffUsers.map((u) => u.name)]} /></div><PreviewTable records={filtered} /></section>
  </div>;
}
function Summary({ icon: Icon, label, value, note, danger, gold }: { icon: typeof Boxes; label: string; value: string; note: string; danger?: boolean; gold?: boolean }) { const tone = danger ? "bg-[#EF4444]/10 text-[#EF4444]" : gold ? "bg-[#D4A017]/12 text-[#A57809]" : "bg-[#16A34A]/10 text-[#16A34A]"; return <article className="rounded-2xl border border-[#DDEAE0] bg-white p-4"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={18} /></span><p className="mt-4 text-[10px] font-black uppercase tracking-wider text-[#789083]">{label}</p><p className={`mt-1 text-lg font-black ${danger ? "text-[#EF4444]" : "text-[#173324]"}`}>{value}</p><p className="mt-1 text-[11px] text-[#789083]">{note}</p></article>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: string[] }) { return <label className="relative"><select aria-label={label} value={value} onChange={(e) => onChange(e.target.value)} className="w-full appearance-none rounded-xl border border-[#DDEAE0] bg-white py-2.5 pl-3 pr-9 text-xs font-bold text-[#60766B]">{options.map((o) => <option key={o}>{o}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#789083]" size={14} /></label>; }
function PreviewTable({ records }: { records: ReportPreview[] }) { return <><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1100px] text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-wider text-[#789083]">{["Date", "Report type", "Branch", "Total sales", "Expenses", "Profit estimate", "Created by", "Status", "Actions"].map((h) => <th key={h} className="px-4 py-3.5">{h}</th>)}</tr></thead><tbody>{records.map((r) => <tr key={r.id} className="border-t border-[#EEF3EF] text-xs text-[#60766B]"><td className="px-4 py-3">{r.date}</td><td className="px-4 py-3 font-black text-[#173324]">{r.type}</td><td className="px-4 py-3">{r.branch}</td><td className="px-4 py-3">{money(r.totalSales)}</td><td className="px-4 py-3 text-[#EF4444]">{money(r.expenses)}</td><td className="px-4 py-3 font-black text-[#0F8C42]">{money(r.profitEstimate)}</td><td className="px-4 py-3">{r.createdBy}</td><td className="px-4 py-3"><Status value={r.status} /></td><td className="px-4 py-3"><MoreHorizontal size={16} /></td></tr>)}</tbody></table></div><div className="grid gap-3 p-3 lg:hidden">{records.map((r) => <article key={r.id} className="rounded-xl border border-[#E8F0EA] p-3"><div className="flex justify-between"><div><p className="text-xs font-black text-[#173324]">{r.type}</p><p className="mt-1 text-[10px] text-[#789083]">{r.branch} · {r.date}</p></div><Status value={r.status} /></div><div className="mt-3 grid grid-cols-3 rounded-lg bg-[#F8FBF8] p-2.5 text-[10px]"><span><b className="block text-[#789083]">Sales</b><strong>{money(r.totalSales)}</strong></span><span><b className="block text-[#789083]">Expenses</b><strong className="text-[#EF4444]">{money(r.expenses)}</strong></span><span><b className="block text-[#789083]">Profit</b><strong className="text-[#0F8C42]">{money(r.profitEstimate)}</strong></span></div></article>)}</div></>; }
function Status({ value }: { value: string }) { return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${value === "Ready" ? "bg-[#16A34A]/10 text-[#0F8C42]" : value === "Generating" ? "bg-[#D4A017]/12 text-[#9A7108]" : "bg-[#789083]/10 text-[#60766B]"}`}>{value}</span>; }
