"use client";

import { useState } from "react";
import { Award, Gift, Medal, Plus, RotateCcw, Sparkles, Star, Users } from "lucide-react";
import { rewardCustomers, rewardRules } from "@/lib/growth-mock-data";

export function RewardsPage() {
  const [feedback, setFeedback] = useState("");
  function addRule() { setFeedback("Reward rule builder placeholder opened."); window.setTimeout(() => setFeedback(""), 2400); }
  const issued = rewardCustomers.reduce((sum, item) => sum + item.points, 0);
  const redeemed = rewardCustomers.reduce((sum, item) => sum + item.redeemed, 0);
  return <div className="mx-auto max-w-[1650px]">
    <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#16A34A]">Customer retention</p><h2 className="mt-1 text-2xl font-black text-[#10271B] md:text-3xl">Rewards</h2><p className="mt-1 text-sm text-[#789083]">Track loyalty points and configure reward rules for repeat customers.</p></div><div><button onClick={addRule} className="flex w-fit items-center gap-2 rounded-xl bg-[#16A34A] px-4 py-3 text-xs font-black text-white"><Plus size={16} />Add reward rule</button>{feedback && <p className="mt-2 text-xs font-bold text-[#16A34A]">{feedback}</p>}</div></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={Users} label="Loyalty customers" value="628" note="Enrolled across all branches" /><Summary icon={Sparkles} label="Points issued" value={issued.toLocaleString()} note="All tracked reward activity" /><Summary icon={RotateCcw} label="Points redeemed" value={redeemed.toLocaleString()} note="Used during checkout" gold /><Summary icon={Gift} label="Available points" value={(issued - redeemed).toLocaleString()} note="Customer reward liability" /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[0.8fr_1.2fr]">
      <article className="rounded-2xl border border-[#DDEAE0] bg-white p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#D4A017]/12 text-[#A57809]"><Medal size={18} /></span><div><h3 className="font-black text-[#173324]">Top loyal customers</h3><p className="text-xs text-[#789083]">Highest available reward balances.</p></div></div><div className="mt-4 space-y-3">{rewardCustomers.slice(0, 4).map((item, index) => <div key={item.name} className="flex items-center gap-3 rounded-xl border border-[#EEF3EF] p-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#16A34A]/10 text-xs font-black text-[#0F8C42]">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-black text-[#173324]">{item.name}</p><p className="mt-1 text-[10px] text-[#789083]">{item.type} customer</p></div><p className="text-xs font-black text-[#A57809]">{item.value.toLocaleString()} pts</p></div>)}</div></article>
      <article className="rounded-2xl border border-[#DDEAE0] bg-white p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#16A34A]/10 text-[#16A34A]"><Award size={18} /></span><div><h3 className="font-black text-[#173324]">Reward rules</h3><p className="text-xs text-[#789083]">Checkout earning rules and bonus placeholders.</p></div></div><div className="mt-4 space-y-3">{rewardRules.map((rule) => <div key={rule.title} className="flex flex-col justify-between gap-3 rounded-xl border border-[#EEF3EF] p-3 sm:flex-row sm:items-center"><div><p className="text-xs font-black text-[#173324]">{rule.title}</p><p className="mt-1 text-[11px] text-[#789083]">{rule.note}</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-black ${rule.status === "Active" ? "bg-[#16A34A]/10 text-[#0F8C42]" : "bg-[#D4A017]/12 text-[#8A670C]"}`}>{rule.status}</span></div>)}</div><button onClick={addRule} className="mt-4 w-full rounded-xl border border-[#DDEAE0] py-3 text-xs font-black text-[#60766B]">Configure loyalty rules</button></article>
    </section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-[#DDEAE0] bg-white"><div className="flex items-center gap-3 border-b border-[#E8F0EA] p-4"><Star size={18} className="text-[#D4A017]" /><div><h3 className="font-black text-[#173324]">Customer rewards</h3><p className="text-xs text-[#789083]">Mock balances available during POS checkout.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-wider text-[#789083]">{["Customer", "Phone", "Type", "Points issued", "Redeemed", "Available", "Last visit", "Status"].map((h) => <th key={h} className="px-4 py-3.5">{h}</th>)}</tr></thead><tbody>{rewardCustomers.map((item) => <tr key={item.name} className="border-t border-[#EEF3EF] text-xs text-[#60766B]"><td className="px-4 py-3 font-black text-[#173324]">{item.name}</td><td className="px-4 py-3">{item.phone}</td><td className="px-4 py-3">{item.type}</td><td className="px-4 py-3">{item.points.toLocaleString()}</td><td className="px-4 py-3">{item.redeemed.toLocaleString()}</td><td className="px-4 py-3 font-black text-[#A57809]">{item.value.toLocaleString()}</td><td className="px-4 py-3">{item.lastVisit}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${item.status === "Active" ? "bg-[#16A34A]/10 text-[#0F8C42]" : "bg-[#789083]/10 text-[#60766B]"}`}>{item.status}</span></td></tr>)}</tbody></table></div></section>
  </div>;
}
function Summary({ icon: Icon, label, value, note, gold }: { icon: typeof Gift; label: string; value: string; note: string; gold?: boolean }) { return <article className="rounded-2xl border border-[#DDEAE0] bg-white p-4"><span className={`grid h-10 w-10 place-items-center rounded-xl ${gold ? "bg-[#D4A017]/12 text-[#A57809]" : "bg-[#16A34A]/10 text-[#16A34A]"}`}><Icon size={18} /></span><p className="mt-4 text-[10px] font-black uppercase tracking-wider text-[#789083]">{label}</p><p className="mt-1 text-lg font-black text-[#173324]">{value}</p><p className="mt-1 text-[11px] text-[#789083]">{note}</p></article>; }
