"use client";

import Link from "next/link";
import { useState } from "react";
import { Building2, Check, ChevronRight, CloudDownload, CreditCard, Image as ImageIcon, Printer, Save, Settings2, ShieldCheck, SlidersHorizontal, Store, Users } from "lucide-react";

const industryModes = ["Retail / Supermarket", "Restaurant", "Cosmetics", "Hardware", "Auto Spares"];

export function SettingsPage() {
  const [mode, setMode] = useState(industryModes[0]);
  const [feedback, setFeedback] = useState("");
  function show(message: string) { setFeedback(message); window.setTimeout(() => setFeedback(""), 2400); }
  return <div className="mx-auto max-w-[1650px]">
    <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#16A34A]">Business configuration</p><h2 className="mt-1 text-2xl font-black text-[#10271B] md:text-3xl">Settings</h2><p className="mt-1 text-sm text-[#789083]">Manage business identity, checkout preferences and system defaults.</p></div><div><button onClick={() => show("Mock business settings saved.")} className="flex w-fit items-center gap-2 rounded-xl bg-[#16A34A] px-4 py-3 text-xs font-black text-white"><Save size={15} />Save settings</button>{feedback && <p className="mt-2 text-xs font-bold text-[#16A34A]">{feedback}</p>}</div></div>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_0.9fr]">
      <div className="space-y-5">
        <Panel icon={Building2} title="Business profile" note="Identity shown on receipts and reports."><div className="grid gap-4 sm:grid-cols-[130px_1fr]"><button onClick={() => show("Business logo upload placeholder opened.")} className="grid min-h-28 place-items-center rounded-xl border border-dashed border-[#C9DACC] bg-[#F8FBF8] text-center text-[#789083]"><span><ImageIcon size={22} className="mx-auto" /><b className="mt-2 block text-[10px]">Business logo</b><span className="mt-1 block text-[9px]">Upload placeholder</span></span></button><div className="grid gap-3 sm:grid-cols-2"><Field label="Business name" value="Biashara Cloud POS Demo" /><Field label="Phone number" value="+254 712 345 678" /><Field label="Email" value="admin@biashara.demo" /><Field label="PIN / VAT number" value="P051234567X" /></div></div></Panel>
        <Panel icon={SlidersHorizontal} title="IndustryOps mode" note="Choose the workflow profile that best matches your operation."><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{industryModes.map((item) => <button key={item} onClick={() => setMode(item)} className={`flex items-center justify-between rounded-xl border p-3 text-left text-xs font-black ${mode === item ? "border-[#16A34A] bg-[#16A34A]/8 text-[#0F8C42]" : "border-[#DDEAE0] text-[#60766B]"}`}>{item}{mode === item && <Check size={15} />}</button>)}</div></Panel>
        <Panel icon={CreditCard} title="Payment methods" note="Select payment options available during checkout."><div className="grid gap-2 sm:grid-cols-2">{["Cash", "M-Pesa", "Bank", "Card", "Credit / Debt"].map((item, index) => <label key={item} className="flex items-center justify-between rounded-xl border border-[#DDEAE0] p-3 text-xs font-bold text-[#60766B]"><span>{item}</span><input type="checkbox" defaultChecked={index !== 3} /></label>)}</div></Panel>
        <Panel icon={Printer} title="Receipt settings" note="Mock receipt formatting controls."><div className="grid gap-3 sm:grid-cols-2"><Field label="Receipt footer" value="Thank you for shopping with us." /><Field label="Invoice prefix" value="INV-" /><Toggle label="Show cashier name" checked /><Toggle label="Print customer balance" checked /></div></Panel>
      </div>
      <div className="space-y-5">
        <Panel icon={Settings2} title="System preferences" note="Cloud POS defaults for daily operations."><div className="space-y-3"><Toggle label="Low stock notifications" checked /><Toggle label="Debt due reminders" checked /><Toggle label="Require till opening balance" checked /><Toggle label="Allow negative stock" /><Toggle label="Email daily closing report" checked /></div></Panel>
        <Panel icon={ShieldCheck} title="Administration shortcuts" note="Jump to team permissions or branch controls."><div className="space-y-2"><Shortcut href="/hrm" icon={Users} title="User permissions" note="Manage roles and access rights" /><Shortcut href="/branches" icon={Store} title="Branch settings" note="Manage locations and assigned tills" /></div></Panel>
        <Panel icon={CloudDownload} title="Backup and data" note="Backend export will be connected in a later phase."><p className="rounded-xl bg-[#FFF9E8] p-3 text-[11px] leading-5 text-[#8A670C]">Cloud backup, restore and full data archive downloads are placeholders until persistent storage is added.</p><button onClick={() => show("Data download placeholder opened.")} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-[#DDEAE0] py-3 text-xs font-black text-[#60766B]"><CloudDownload size={15} />Download data archive</button></Panel>
      </div>
    </section>
  </div>;
}
function Panel({ icon: Icon, title, note, children }: { icon: typeof Building2; title: string; note: string; children: React.ReactNode }) { return <article className="rounded-2xl border border-[#DDEAE0] bg-white p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#16A34A]/10 text-[#16A34A]"><Icon size={18} /></span><div><h3 className="font-black text-[#173324]">{title}</h3><p className="text-xs text-[#789083]">{note}</p></div></div><div className="mt-4">{children}</div></article>; }
function Field({ label, value }: { label: string; value: string }) { return <label><span className="text-[10px] font-black uppercase tracking-wider text-[#789083]">{label}</span><input defaultValue={value} className="mt-2 w-full rounded-xl border border-[#DDEAE0] px-3 py-3 text-xs font-bold text-[#173324] outline-none focus:border-[#16A34A]" /></label>; }
function Toggle({ label, checked }: { label: string; checked?: boolean }) { return <label className="flex items-center justify-between rounded-xl border border-[#DDEAE0] p-3 text-xs font-bold text-[#60766B]"><span>{label}</span><input type="checkbox" defaultChecked={checked} /></label>; }
function Shortcut({ href, icon: Icon, title, note }: { href: string; icon: typeof Users; title: string; note: string }) { return <Link href={href} className="flex items-center gap-3 rounded-xl border border-[#DDEAE0] p-3 hover:border-[#16A34A]/50"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#16A34A]/10 text-[#16A34A]"><Icon size={16} /></span><span className="flex-1"><b className="block text-xs text-[#173324]">{title}</b><span className="mt-1 block text-[10px] text-[#789083]">{note}</span></span><ChevronRight size={15} className="text-[#789083]" /></Link>; }
