"use client";

import { useState } from "react";
import { AlertTriangle, BellRing, ChevronDown, FileText, Megaphone, MessageSquareText, Plus, Send, Users } from "lucide-react";
import { smsCampaigns, smsCustomerGroups, smsTemplates } from "@/lib/growth-mock-data";

export function SmsMarketingPage() {
  const [template, setTemplate] = useState(smsTemplates[0]);
  const [feedback, setFeedback] = useState("");
  function placeholder(message: string) { setFeedback(message); window.setTimeout(() => setFeedback(""), 2400); }
  return <div className="mx-auto max-w-[1700px]">
    <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#16A34A]">Customer communication</p><h2 className="mt-1 text-2xl font-black text-[#10271B] md:text-3xl">SMS Marketing</h2><p className="mt-1 text-sm text-[#789083]">Prepare promotions, account reminders and operational text alerts.</p></div><div><button onClick={() => placeholder("Campaign composer placeholder opened.")} className="flex w-fit items-center gap-2 rounded-xl bg-[#16A34A] px-4 py-3 text-xs font-black text-white"><Plus size={16} />Create campaign</button>{feedback && <p className="mt-2 text-xs font-bold text-[#16A34A]">{feedback}</p>}</div></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={MessageSquareText} label="SMS credits" value="8,420" note="Placeholder account balance" /><Summary icon={Send} label="SMS sent this month" value="6,284" note="Delivery records across campaigns" /><Summary icon={Megaphone} label="Active campaigns" value="3" note="Promotions and reminders" gold /><Summary icon={Users} label="Reachable customers" value="1,480" note="Customers with valid phone numbers" /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[0.85fr_1.15fr]">
      <article className="rounded-2xl border border-[#DDEAE0] bg-white p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#16A34A]/10 text-[#16A34A]"><Users size={18} /></span><div><h3 className="font-black text-[#173324]">Customer groups</h3><p className="text-xs text-[#789083]">Audience segments for targeted communication.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-1">{smsCustomerGroups.map((group) => <div key={group.name} className="rounded-xl border border-[#EEF3EF] p-3"><div className="flex justify-between gap-3"><p className="text-xs font-black text-[#173324]">{group.name}</p><span className="rounded-full bg-[#16A34A]/10 px-2 py-1 text-[10px] font-black text-[#0F8C42]">{group.contacts}</span></div><p className="mt-1 text-[11px] leading-5 text-[#789083]">{group.note}</p></div>)}</div></article>
      <article className="rounded-2xl border border-[#DDEAE0] bg-white p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#D4A017]/12 text-[#A57809]"><FileText size={18} /></span><div><h3 className="font-black text-[#173324]">Message template preview</h3><p className="text-xs text-[#789083]">Select a common business communication template.</p></div></div><div className="mt-4 flex flex-wrap gap-2">{smsTemplates.map((item) => <button key={item.title} onClick={() => setTemplate(item)} className={`rounded-lg px-3 py-2 text-[10px] font-black ${template.title === item.title ? "bg-[#12311F] text-white" : "border border-[#DDEAE0] text-[#60766B]"}`}>{item.title}</button>)}</div><div className="mt-4 rounded-xl border border-[#DDEAE0] bg-[#F8FBF8] p-4"><p className="text-[10px] font-black uppercase tracking-wider text-[#789083]">Audience: {template.audience}</p><p className="mt-3 text-sm leading-6 text-[#173324]">{template.message}</p></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => placeholder("Test SMS placeholder opened.")} className="rounded-xl bg-[#16A34A] px-4 py-3 text-xs font-black text-white">Send test SMS</button><button onClick={() => placeholder("Template save placeholder opened.")} className="rounded-xl border border-[#DDEAE0] px-4 py-3 text-xs font-black text-[#60766B]">Save template</button></div></article>
    </section>
    <section className="mt-5 grid gap-3 md:grid-cols-3"><Action icon={BellRing} title="Debt reminder SMS" note="Notify customers with outstanding or overdue balances." /><Action icon={Megaphone} title="Promotion SMS" note="Share branch offers with selected customer groups." /><Action icon={AlertTriangle} title="Low stock alert SMS" note="Placeholder alert for managers when products run low." /></section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-[#DDEAE0] bg-white"><div className="flex items-center gap-3 border-b border-[#E8F0EA] p-4"><MessageSquareText size={18} className="text-[#16A34A]" /><div><h3 className="font-black text-[#173324]">SMS campaigns</h3><p className="text-xs text-[#789083]">Mock send history and draft campaigns.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[960px] text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-wider text-[#789083]">{["Campaign", "Type", "Audience", "Recipients", "Sent", "Created by", "Date", "Status", ""].map((h) => <th key={h} className="px-4 py-3.5">{h}</th>)}</tr></thead><tbody>{smsCampaigns.map((item) => <tr key={item.id} className="border-t border-[#EEF3EF] text-xs text-[#60766B]"><td className="px-4 py-3"><p className="font-black text-[#173324]">{item.name}</p><p className="mt-1 text-[10px] text-[#789083]">{item.id}</p></td><td className="px-4 py-3">{item.type}</td><td className="px-4 py-3">{item.audience}</td><td className="px-4 py-3">{item.recipients.toLocaleString()}</td><td className="px-4 py-3">{item.sent.toLocaleString()}</td><td className="px-4 py-3">{item.createdBy}</td><td className="px-4 py-3">{item.date}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${item.status === "Sent" ? "bg-[#16A34A]/10 text-[#0F8C42]" : "bg-[#D4A017]/12 text-[#8A670C]"}`}>{item.status}</span></td><td className="px-4 py-3"><button aria-label={`Open ${item.name}`} className="text-[#789083]"><ChevronDown size={15} /></button></td></tr>)}</tbody></table></div></section>
  </div>;
}
function Summary({ icon: Icon, label, value, note, gold }: { icon: typeof Send; label: string; value: string; note: string; gold?: boolean }) { return <article className="rounded-2xl border border-[#DDEAE0] bg-white p-4"><span className={`grid h-10 w-10 place-items-center rounded-xl ${gold ? "bg-[#D4A017]/12 text-[#A57809]" : "bg-[#16A34A]/10 text-[#16A34A]"}`}><Icon size={18} /></span><p className="mt-4 text-[10px] font-black uppercase tracking-wider text-[#789083]">{label}</p><p className="mt-1 text-lg font-black text-[#173324]">{value}</p><p className="mt-1 text-[11px] text-[#789083]">{note}</p></article>; }
function Action({ icon: Icon, title, note }: { icon: typeof BellRing; title: string; note: string }) { return <article className="rounded-2xl border border-[#DDEAE0] bg-white p-4"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#16A34A]/10 text-[#16A34A]"><Icon size={16} /></span><h3 className="mt-3 text-xs font-black text-[#173324]">{title}</h3><p className="mt-1 text-[11px] leading-5 text-[#789083]">{note}</p></article>; }
