"use client";

import { useState } from "react";
import { Check, ChevronRight, Crown, Gauge, ReceiptText } from "lucide-react";
import { subscriptionPayments, subscriptionPlans, subscriptionUsage } from "@/lib/growth-mock-data";

function money(value: number) { return `Ksh ${new Intl.NumberFormat("en-KE").format(value)}`; }

export function SubscriptionsPage() {
  const [feedback, setFeedback] = useState("");
  function show(message: string) { setFeedback(message); window.setTimeout(() => setFeedback(""), 2400); }
  return <div className="mx-auto max-w-[1700px]">
    <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#16A34A]">Billing and usage</p><h2 className="mt-1 text-2xl font-black text-[#10271B] md:text-3xl">Subscriptions</h2><p className="mt-1 text-sm text-[#789083]">Review your plan, usage limits and cloud subscription payments.</p></div>{feedback && <p className="rounded-xl bg-[#16A34A]/10 px-4 py-3 text-xs font-black text-[#0F8C42]">{feedback}</p>}</div>
    <section className="grid gap-4 xl:grid-cols-[1.2fr_0.8fr]">
      <article className="overflow-hidden rounded-2xl bg-[#0E2418] p-5 text-[#F6FFF8] shadow-lg shadow-[#12311F]/10"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-[#D4A017]">Current plan</p><div className="mt-3 flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#22C55E]/15 text-[#22C55E]"><Crown size={22} /></span><div><h3 className="text-xl font-black">Business Plan</h3><p className="mt-1 text-xs text-[#B8C7BD]">Active subscription for multi-team operations</p></div></div></div><div className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 sm:min-w-48"><p className="text-[10px] font-black uppercase tracking-wider text-[#B8C7BD]">Renewal date</p><p className="mt-1 text-sm font-black">02 July 2026</p><p className="mt-1 text-[10px] text-[#22C55E]">Subscription status: Active</p></div></div><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => show("Subscription renewal placeholder opened.")} className="rounded-xl bg-[#16A34A] px-4 py-3 text-xs font-black text-white">Renew subscription</button><button onClick={() => show("Plan change request placeholder opened.")} className="rounded-xl border border-white/15 px-4 py-3 text-xs font-black text-[#F6FFF8]">Manage billing</button></div></article>
      <article className="rounded-2xl border border-[#DDEAE0] bg-white p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#D4A017]/12 text-[#A57809]"><Gauge size={18} /></span><div><h3 className="font-black text-[#173324]">Usage limits</h3><p className="text-xs text-[#789083]">Current Business Plan consumption.</p></div></div><div className="mt-4 space-y-3">{subscriptionUsage.map((item) => <div key={item.label}><div className="flex justify-between text-[11px] font-bold"><span className="text-[#60766B]">{item.label}</span><span className="text-[#173324]">{item.used.toLocaleString()} / {item.limit}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-[#E8F0EA]"><div className={`h-full rounded-full ${item.percent >= 100 ? "bg-[#D4A017]" : "bg-[#16A34A]"}`} style={{ width: `${item.percent}%` }} /></div></div>)}</div></article>
    </section>
    <section className="mt-5"><div><h3 className="font-black text-[#173324]">Choose a package</h3><p className="text-xs text-[#789083]">Upgrade or downgrade when your operation changes.</p></div><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{subscriptionPlans.map((plan) => <article key={plan.name} className={`relative rounded-2xl border bg-white p-4 ${plan.featured ? "border-[#16A34A] shadow-md shadow-[#16A34A]/10" : "border-[#DDEAE0]"}`}>{plan.featured && <span className="absolute right-3 top-3 rounded-full bg-[#16A34A]/10 px-2 py-1 text-[9px] font-black uppercase tracking-wider text-[#0F8C42]">Current</span>}<h4 className="text-sm font-black text-[#173324]">{plan.name}</h4><p className="mt-3 text-lg font-black text-[#173324]">{plan.price === null ? "Contact us" : money(plan.price)}{plan.price !== null && <span className="text-[10px] text-[#789083]"> / month</span>}</p><p className="mt-2 min-h-10 text-[11px] leading-5 text-[#789083]">{plan.note}</p><div className="mt-3 space-y-2">{plan.limits.map((limit) => <p key={limit} className="flex gap-2 text-[10px] font-bold text-[#60766B]"><Check size={13} className="shrink-0 text-[#16A34A]" />{limit}</p>)}</div><button onClick={() => show(`${plan.name} plan action is a billing placeholder.`)} className={`mt-4 flex w-full items-center justify-center gap-1 rounded-xl py-2.5 text-[11px] font-black ${plan.featured ? "bg-[#E8F0EA] text-[#60766B]" : "bg-[#16A34A] text-white"}`}>{plan.featured ? "Current package" : plan.name === "Custom / Enterprise" ? "Contact sales" : "Choose plan"}<ChevronRight size={13} /></button></article>)}</div></section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-[#DDEAE0] bg-white"><div className="flex items-center gap-3 border-b border-[#E8F0EA] p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#16A34A]/10 text-[#16A34A]"><ReceiptText size={18} /></span><div><h3 className="font-black text-[#173324]">Payment history</h3><p className="text-xs text-[#789083]">Mock subscription renewal records.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-wider text-[#789083]">{["Payment ID", "Date", "Plan", "Billing period", "Method", "Amount", "Status"].map((h) => <th key={h} className="px-4 py-3.5">{h}</th>)}</tr></thead><tbody>{subscriptionPayments.map((item) => <tr key={item.id} className="border-t border-[#EEF3EF] text-xs text-[#60766B]"><td className="px-4 py-3 font-black text-[#173324]">{item.id}</td><td className="px-4 py-3">{item.date}</td><td className="px-4 py-3">{item.plan}</td><td className="px-4 py-3">{item.period}</td><td className="px-4 py-3">{item.method}</td><td className="px-4 py-3 font-black text-[#173324]">{money(item.amount)}</td><td className="px-4 py-3"><span className="rounded-full bg-[#16A34A]/10 px-2.5 py-1 text-[10px] font-black text-[#0F8C42]">{item.status}</span></td></tr>)}</tbody></table></div></section>
  </div>;
}
