import Link from "next/link";
import { PrintButton } from "@/components/print-button";
import { InfoCard, MetricGrid, ProfileHeader, TransactionTable, formatCurrency } from "@/components/profile-ui";
import type { SupplierProfileData } from "@/lib/profile-data";

export function SupplierProfilePage({ supplier }: { supplier: SupplierProfileData }) {
  return (
    <div className="mx-auto max-w-[1500px]">
      <ProfileHeader
        eyebrow="Supplier profile"
        title={supplier.name}
        subtitle={`${supplier.businessName} - ${supplier.category}`}
        backHref="/suppliers"
        backLabel="Back to suppliers"
        actions={
          <>
            <Link href="/suppliers" className="rounded-xl border border-[#DDEAE0] bg-white px-4 py-3 text-xs font-black text-[#60766B] hover:bg-[#F8FBF8]">Edit supplier</Link>
            <Link href="/purchases" className="rounded-xl bg-[#16A34A] px-4 py-3 text-xs font-black text-white hover:bg-[#12883E]">Add purchase</Link>
            <a href="#statement" className="rounded-xl border border-[#D4A017]/40 bg-[#FFF9E8] px-4 py-3 text-xs font-black text-[#8A670C]">View statement</a>
            <PrintButton />
          </>
        }
      />
      <MetricGrid metrics={supplier.metrics} />
      <section className="mt-5 grid gap-5 xl:grid-cols-[0.85fr_1.15fr]">
        <InfoCard title="Supplier details" rows={[
          ["Phone", supplier.phone],
          ["Email", supplier.email],
          ["Status", supplier.status],
          ["Created", supplier.createdAt],
          ["Balance", formatCurrency(supplier.balance)],
        ]} />
        <article className="rounded-2xl border border-[#DDEAE0] bg-white p-5">
          <h3 className="text-sm font-black text-[#173324]">Notes</h3>
          <div className="mt-4 space-y-2">
            {supplier.notes.map((note) => <p key={note} className="rounded-xl bg-[#F8FBF8] px-4 py-3 text-xs font-bold text-[#60766B]">{note}</p>)}
          </div>
        </article>
      </section>
      <section id="statement" className="mt-5 space-y-5 scroll-mt-24">
        <article className="rounded-2xl border border-[#DDEAE0] bg-white p-5">
          <p className="text-[10px] font-black uppercase tracking-wider text-[#789083]">Printable statement</p>
          <h3 className="mt-1 text-lg font-black text-[#173324]">{supplier.name} statement</h3>
          <p className="mt-1 text-xs text-[#789083]">Generated by LeadsStacks POS. Purchase payments currently reduce supplier balance through purchase records.</p>
        </article>
        <TransactionTable title="Purchase history" empty="No purchases recorded for this supplier yet." rows={supplier.purchases} />
      </section>
    </div>
  );
}

