"use client";

import { useState } from "react";
import { Calculator, FileText, Landmark, ReceiptText, Save, Settings2, ShieldCheck } from "lucide-react";
import { taxRecords } from "@/lib/finance-mock-data";

function money(value: number) { return new Intl.NumberFormat("en-KE", { style: "currency", currency: "KES", maximumFractionDigits: 0 }).format(value); }

export function TaxSettingsPage() {
  const [vatEnabled, setVatEnabled] = useState(true); const [inclusive, setInclusive] = useState(true);
  const collected = taxRecords.reduce((sum, item) => sum + item.vatCollected, 0); const invoices = taxRecords.reduce((sum, item) => sum + item.invoices, 0);
  return <div className="mx-auto max-w-[1500px]"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#16A34A]">Compliance settings</p><h2 className="mt-1 text-2xl font-black text-[#10271B] md:text-3xl">Tax Settings</h2><p className="mt-1 text-sm text-[#789083]">Configure VAT, invoice numbering and tax integration placeholders.</p></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={Calculator} label="VAT rate" value="16%" note="Kenya VAT placeholder" /><Summary icon={ReceiptText} label="Tax invoices" value={`${invoices}`} note="Invoices across tracked periods" /><Summary icon={Landmark} label="VAT collected" value={money(collected)} note="Mock tax ledger total" /><Summary icon={ShieldCheck} label="eTIMS status" value="Not connected" note="Integration placeholder" gold /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[0.9fr_1.1fr]"><article className="rounded-2xl border border-[#DDEAE0] bg-white p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#16A34A]/10 text-[#16A34A]"><Settings2 size={18} /></span><div><h3 className="font-black text-[#173324]">Tax configuration</h3><p className="text-xs text-[#789083]">Mock settings for your business invoices.</p></div></div><div className="mt-5 space-y-3"><Toggle label="VAT enabled" note="Apply VAT calculations during checkout" checked={vatEnabled} onChange={setVatEnabled} /><Field label="VAT rate" value="16%" /><Toggle label="Tax inclusive pricing" note={inclusive ? "Prices include VAT" : "VAT added at checkout"} checked={inclusive} onChange={setInclusive} /><Field label="Tax invoice prefix" value="TAX-INV-" /><Field label="Next invoice number" value="0002849" /><div className="rounded-xl border border-[#D4A017]/35 bg-[#FFF9E8] p-3"><p className="text-xs font-black text-[#8A670C]">eTIMS integration placeholder</p><p className="mt-1 text-[11px] leading-5 text-[#9A7108]">API credentials and fiscal submission will be configured after the backend phase.</p><button className="mt-3 rounded-lg border border-[#D4A017]/40 bg-white px-3 py-2 text-[10px] font-black text-[#8A670C]">Configure later</button></div><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#16A34A] py-3 text-xs font-black text-white"><Save size={15} />Save tax settings</button></div></article>
      <article className="overflow-hidden rounded-2xl border border-[#DDEAE0] bg-white"><div className="flex items-center gap-3 border-b border-[#E8F0EA] p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#16A34A]/10 text-[#16A34A]"><FileText size={18} /></span><div><h3 className="font-black text-[#173324]">Tax records</h3><p className="text-xs text-[#789083]">VAT summary by reporting period.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-wider text-[#789083]">{["Record", "Period", "Taxable sales", "VAT collected", "Invoices", "Status"].map((h) => <th key={h} className="px-4 py-3.5">{h}</th>)}</tr></thead><tbody>{taxRecords.map((r) => <tr key={r.id} className="border-t border-[#EEF3EF] text-xs text-[#60766B]"><td className="px-4 py-3 font-black text-[#173324]">{r.id}</td><td className="px-4 py-3">{r.period}</td><td className="px-4 py-3">{money(r.taxableSales)}</td><td className="px-4 py-3 font-black text-[#173324]">{money(r.vatCollected)}</td><td className="px-4 py-3">{r.invoices}</td><td className="px-4 py-3"><span className="rounded-full bg-[#16A34A]/10 px-2.5 py-1 text-[10px] font-black text-[#0F8C42]">{r.status}</span></td></tr>)}</tbody></table></div></article>
    </section>
  </div>;
}
function Summary({ icon: Icon, label, value, note, gold }: { icon: typeof ReceiptText; label: string; value: string; note: string; gold?: boolean }) { return <article className="rounded-2xl border border-[#DDEAE0] bg-white p-4"><span className={`grid h-10 w-10 place-items-center rounded-xl ${gold ? "bg-[#D4A017]/12 text-[#A57809]" : "bg-[#16A34A]/10 text-[#16A34A]"}`}><Icon size={18} /></span><p className="mt-4 text-[10px] font-black uppercase tracking-wider text-[#789083]">{label}</p><p className="mt-1 text-lg font-black text-[#173324]">{value}</p><p className="mt-1 text-[11px] text-[#789083]">{note}</p></article>; }
function Toggle({ label, note, checked, onChange }: { label: string; note: string; checked: boolean; onChange: (v: boolean) => void }) { return <label className="flex items-center justify-between rounded-xl border border-[#DDEAE0] p-3"><span><b className="block text-xs text-[#173324]">{label}</b><span className="mt-1 block text-[10px] text-[#789083]">{note}</span></span><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /></label>; }
function Field({ label, value }: { label: string; value: string }) { return <label><span className="text-[10px] font-black uppercase tracking-wider text-[#789083]">{label}</span><input defaultValue={value} className="mt-2 w-full rounded-xl border border-[#DDEAE0] px-3 py-3 text-xs font-bold text-[#173324] outline-none focus:border-[#16A34A]" /></label>; }
