"use client";

import { useMemo, useState } from "react";
import { ArrowLeftRight, Ban, CheckCircle2, ChevronDown, Clock3, MoreHorizontal, Plus, Search, Truck, X } from "lucide-react";
import { stockTransfers, warehouses, warehouseProducts, type StockTransfer, type TransferStatus } from "@/lib/inventory-mock-data";

export function TransfersPage() {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("All statuses"); const [open, setOpen] = useState(false);
  const filtered = useMemo(() => { const n = query.trim().toLowerCase(); return stockTransfers.filter((item) => (status === "All statuses" || item.status === status) && (!n || `${item.id} ${item.product} ${item.from} ${item.to}`.toLowerCase().includes(n))); }, [query, status]);
  const count = (value: TransferStatus) => stockTransfers.filter((item) => item.status === value).length;
  return <div className="mx-auto max-w-[1700px]"><div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#16A34A]">Stock movement</p><h2 className="mt-1 text-2xl font-black text-[#10271B] md:text-3xl">Transfer</h2><p className="mt-1 text-sm text-[#789083]">Move products safely between warehouses and branches.</p></div><button onClick={() => setOpen(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[#16A34A] px-4 py-3 text-xs font-black text-white"><Plus size={16} />Create transfer</button></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={ArrowLeftRight} label="Total transfers" value={`${stockTransfers.length} records`} note="All warehouse movements" /><Summary icon={Clock3} label="Pending transfers" value={`${count("Pending")} records`} note="Awaiting approval" gold /><Summary icon={CheckCircle2} label="Completed transfers" value={`${count("Completed")} records`} note="Stock successfully received" /><Summary icon={Ban} label="Cancelled transfers" value={`${count("Cancelled")} records`} note="Cancelled movement requests" danger /></section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-[#DDEAE0] bg-white shadow-sm shadow-[#12311F]/5"><div className="grid gap-3 border-b border-[#E8F0EA] p-4 lg:grid-cols-[minmax(0,1fr)_190px]"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#789083]" size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} aria-label="Search transfers" placeholder="Search transfer, product or warehouse..." className="w-full rounded-xl border border-[#DDEAE0] bg-[#F8FBF8] py-2.5 pl-9 pr-3 text-xs outline-none focus:border-[#16A34A]" /></label><label className="relative"><select value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Filter transfer status" className="w-full appearance-none rounded-xl border border-[#DDEAE0] bg-white py-2.5 pl-3 pr-9 text-xs font-bold text-[#60766B]"><option>All statuses</option><option>Pending</option><option>In transit</option><option>Completed</option><option>Cancelled</option></select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#789083]" size={14} /></label></div>
      <div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1320px] border-collapse text-left"><thead><tr className="bg-[#F8FBF8] text-[10px] font-black uppercase tracking-[0.13em] text-[#789083]"><th className="px-4 py-3.5">Transfer ID</th><th className="px-3 py-3.5">Product</th><th className="px-3 py-3.5">Quantity</th><th className="px-3 py-3.5">From warehouse / branch</th><th className="px-3 py-3.5">To warehouse / branch</th><th className="px-3 py-3.5">Requested by</th><th className="px-3 py-3.5">Approved by</th><th className="px-3 py-3.5">Date</th><th className="px-3 py-3.5">Status</th><th className="px-4 py-3.5 text-right">Actions</th></tr></thead><tbody>{filtered.map((item) => <TransferRow key={item.id} item={item} />)}</tbody></table></div><div className="grid gap-3 p-3 lg:hidden">{filtered.map((item) => <TransferCard key={item.id} item={item} />)}</div><footer className="border-t border-[#E8F0EA] p-4 text-xs text-[#789083]">Showing <b className="text-[#173324]">{filtered.length}</b> of <b className="text-[#173324]">{stockTransfers.length}</b> transfers</footer>
    </section>{open && <TransferDialog onClose={() => setOpen(false)} />}
  </div>;
}
function Summary({ icon: Icon, label, value, note, danger, gold }: { icon: typeof Truck; label: string; value: string; note: string; danger?: boolean; gold?: boolean }) { const tone = danger ? "bg-[#EF4444]/10 text-[#EF4444]" : gold ? "bg-[#D4A017]/12 text-[#A57809]" : "bg-[#16A34A]/10 text-[#16A34A]"; return <article className="rounded-2xl border border-[#DDEAE0] bg-white p-4"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={18} /></span><p className="mt-4 text-[10px] font-black uppercase tracking-[0.13em] text-[#789083]">{label}</p><p className={`mt-1 text-lg font-black ${danger ? "text-[#EF4444]" : "text-[#173324]"}`}>{value}</p><p className="mt-1 text-[11px] text-[#789083]">{note}</p></article>; }
function TransferRow({ item }: { item: StockTransfer }) { return <tr className="border-t border-[#EEF3EF] text-xs text-[#60766B] hover:bg-[#FBFDFB]"><td className="px-4 py-3 font-black text-[#173324]">{item.id}</td><td className="px-3 py-3 font-semibold">{item.product}</td><td className="px-3 py-3 font-black text-[#173324]">{item.quantity}</td><td className="px-3 py-3">{item.from}</td><td className="px-3 py-3">{item.to}</td><td className="px-3 py-3">{item.requestedBy}</td><td className="px-3 py-3">{item.approvedBy}</td><td className="px-3 py-3">{item.date}</td><td className="px-3 py-3"><TransferBadge status={item.status} /></td><td className="px-4 py-3 text-right"><MoreHorizontal size={16} /></td></tr>; }
function TransferCard({ item }: { item: StockTransfer }) { return <article className="rounded-xl border border-[#E8F0EA] p-3"><div className="flex justify-between"><div><p className="text-xs font-black text-[#173324]">{item.id} · {item.product}</p><p className="mt-1 text-[10px] text-[#789083]">{item.quantity} units · {item.date}</p></div><TransferBadge status={item.status} /></div><div className="mt-3 rounded-lg bg-[#F8FBF8] p-2.5 text-[10px]"><p><b className="text-[#789083]">From:</b> <strong className="text-[#173324]">{item.from}</strong></p><p className="mt-1"><b className="text-[#789083]">To:</b> <strong className="text-[#173324]">{item.to}</strong></p></div></article>; }
function TransferBadge({ status }: { status: TransferStatus }) { const tone = status === "Completed" ? "bg-[#16A34A]/10 text-[#0F8C42]" : status === "Cancelled" ? "bg-[#EF4444]/10 text-[#EF4444]" : "bg-[#D4A017]/12 text-[#9A7108]"; return <span className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-black ${tone}`}>{status}</span>; }
function TransferDialog({ onClose }: { onClose: () => void }) { return <div className="fixed inset-0 z-[70] grid place-items-center bg-[#07120D]/65 p-4"><article className="w-full max-w-md rounded-2xl bg-white"><div className="flex items-center justify-between border-b border-[#E8F0EA] p-4"><div><h3 className="text-sm font-black text-[#173324]">Create stock transfer</h3><p className="mt-0.5 text-[10px] text-[#789083]">Placeholder flow only. Stock will not move.</p></div><button onClick={onClose}><X size={16} /></button></div><div className="grid gap-3 p-4 sm:grid-cols-2"><Field label="Product" options={warehouseProducts.map((item) => item.name)} /><Field label="Quantity" /><Field label="From warehouse" options={warehouses.map((item) => item.name)} /><Field label="To warehouse" options={warehouses.map((item) => item.name)} /><label className="sm:col-span-2"><span className="text-[10px] font-black uppercase tracking-wider text-[#789083]">Transfer note</span><input className="mt-2 w-full rounded-xl border border-[#DDEAE0] px-3 py-3 text-xs outline-none focus:border-[#16A34A]" placeholder="Reason for transfer" /></label><button className="sm:col-span-2 rounded-xl bg-[#16A34A] py-3 text-xs font-black text-white">Save mock transfer</button></div></article></div>; }
function Field({ label, options }: { label: string; options?: string[] }) { return <label><span className="text-[10px] font-black uppercase tracking-wider text-[#789083]">{label}</span>{options ? <select className="mt-2 w-full rounded-xl border border-[#DDEAE0] px-3 py-3 text-xs outline-none">{options.map((item) => <option key={item}>{item}</option>)}</select> : <input className="mt-2 w-full rounded-xl border border-[#DDEAE0] px-3 py-3 text-xs outline-none" placeholder="Enter quantity" />}</label>; }
