"use client";
import Link from "next/link";
import { useState } from "react";
import { Menu, X, ChevronDown, Phone, MessageCircle } from "lucide-react";
import { CONTACT, industries, marketingNavigation } from "@/lib/marketing/site";
import { trackMarketingEvent } from "./analytics";

const { products: productLinks, resources: resourceLinks, utility: utilityLinks } = marketingNavigation;
const mobileLinks = [...productLinks, ...utilityLinks.slice(0, 2), ...resourceLinks, ...utilityLinks.slice(2)];
export function MarketingHeader() { const [open,setOpen]=useState(false); return <header className="sticky top-0 z-50 border-b border-emerald-950/10 bg-white/95 backdrop-blur"><nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3.5 sm:px-6" aria-label="Primary"><Link href="/" className="flex items-center gap-2.5" aria-label="LeadsStacks home"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-700 text-sm font-black text-white">LS</span><span className="text-lg font-black tracking-tight text-emerald-950">LeadsStacks</span></Link><div className="hidden items-center gap-6 lg:flex"><Dropdown label="Products" links={productLinks}/><Dropdown label="Solutions" links={industries.map(item=>({href:`/solutions/${item.slug}`,label:item.name}))}/><Link href="/pricing" className="text-sm font-semibold text-slate-700">Pricing</Link><Dropdown label="Resources" links={resourceLinks}/><Link href="/about" className="text-sm font-semibold text-slate-700">About</Link><Link href="/contact" className="text-sm font-semibold text-slate-700">Contact</Link></div><div className="hidden items-center gap-3 lg:flex"><Link href="/login" className="text-sm font-bold text-slate-700">Sign In</Link><Link onClick={()=>trackMarketingEvent("start_trial")} href="/signup" className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white">Start Free Trial</Link></div><button className="grid h-10 w-10 place-items-center rounded-lg text-emerald-950 lg:hidden" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></nav>{open&&<div className="border-t border-emerald-950/10 bg-white px-4 pb-5 lg:hidden"><div className="mx-auto grid max-w-7xl gap-1 pt-3">{mobileLinks.map(link=><Link key={link.href} href={link.href} onClick={()=>setOpen(false)} className="rounded-lg px-3 py-2.5 text-sm font-semibold text-slate-700 hover:bg-emerald-50">{link.label}</Link>)}<Link href="/signup" className="mt-2 rounded-xl bg-emerald-700 px-4 py-3 text-center text-sm font-bold text-white">Start Free Trial</Link></div></div>}</header>; }
function Dropdown({ label, links }: { label: string; links: readonly {href:string;label:string}[] }) { return <details className="group relative"><summary className="flex cursor-pointer list-none items-center gap-1 text-sm font-semibold text-slate-700 hover:text-emerald-700">{label}<ChevronDown size={15}/></summary><div className="absolute left-0 top-8 grid w-60 gap-1 rounded-xl border border-emerald-950/10 bg-white p-2 shadow-xl">{links.map((link) => <Link key={link.href} href={link.href} className="rounded-lg px-3 py-2 text-sm text-slate-700 hover:bg-emerald-50 hover:text-emerald-800">{link.label}</Link>)}</div></details> }
export function MarketingFooter() { return <footer className="bg-emerald-950 text-emerald-50"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:px-6 md:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-1"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-600 text-xs font-black">LS</span><span className="font-black">LeadsStacks</span></div><p className="mt-4 text-sm leading-6 text-emerald-100/70">Business management software for growing African businesses.</p></div><FooterColumn title="Product" links={[{href:"/features",label:"Features"},{href:"/pricing",label:"Pricing"},{href:"/login",label:"Sign In"},{href:"/signup",label:"Start Free Trial"}]}/><FooterColumn title="Industries" links={industries.slice(0,7).map(i=>({href:`/solutions/${i.slug}`,label:i.name}))}/><FooterColumn title="Resources" links={[{href:"/blog",label:"Blog"},{href:"/features#faq",label:"FAQs"},{href:"/contact",label:"Contact"}]}/><div><h2 className="text-sm font-bold">Contact</h2><a href={`tel:${CONTACT.tel}`} className="mt-4 flex gap-2 text-sm text-emerald-100/75 hover:text-white"><Phone size={16}/>{CONTACT.phone}</a><a href={CONTACT.whatsapp} onClick={() => trackMarketingEvent("whatsapp_click")} className="mt-3 flex gap-2 text-sm text-emerald-100/75 hover:text-white"><MessageCircle size={16}/>WhatsApp us</a><a href={`mailto:${CONTACT.salesEmail}`} className="mt-3 block text-sm text-emerald-100/75 hover:text-white">{CONTACT.salesEmail}</a><address className="mt-3 text-sm not-italic leading-6 text-emerald-100/75">{CONTACT.address.map((line)=><span key={line} className="block">{line}</span>)}</address></div></div><div className="border-t border-white/10 px-4 py-5 text-center text-xs text-emerald-100/60">© LeadsStacks 2026</div></footer> }
function FooterColumn({title,links}:{title:string;links:{href:string;label:string}[]}) { return <div><h2 className="text-sm font-bold">{title}</h2><ul className="mt-4 space-y-2.5">{links.map(link=><li key={link.href}><Link href={link.href} className="text-sm text-emerald-100/70 hover:text-white">{link.label}</Link></li>)}</ul></div> }
export function MarketingLayout({children}:{children:React.ReactNode}) { return <><MarketingHeader/><main>{children}</main><MarketingFooter/></> }
