import { jsPDF } from "jspdf";

export type ExportValue = string | number | null | undefined;
export type ExportRow = Record<string, ExportValue>;

type PdfOptions = {
  filename: string;
  title: string;
  summary?: Record<string, ExportValue>;
  rows: ExportRow[];
};

function normalizeFilename(filename: string, extension: string) {
  return filename.toLowerCase().endsWith(extension) ? filename : `${filename}${extension}`;
}

function printable(value: ExportValue) {
  return value === null || value === undefined ? "" : String(value);
}

function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function exportToCsv(filename: string, rows: ExportRow[]) {
  if (rows.length === 0) return false;
  const headers = Object.keys(rows[0]);
  const escapeCell = (value: ExportValue) => `"${printable(value).replace(/"/g, '""')}"`;
  const csv = [
    headers.map(escapeCell).join(","),
    ...rows.map((row) => headers.map((header) => escapeCell(row[header])).join(",")),
  ].join("\r\n");

  downloadBlob(normalizeFilename(filename, ".csv"), new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8;" }));
  return true;
}

export function exportReportToPdf({ filename, title, summary = {}, rows }: PdfOptions) {
  const document = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const margin = 36;
  const pageWidth = document.internal.pageSize.getWidth();
  const pageHeight = document.internal.pageSize.getHeight();
  const contentWidth = pageWidth - margin * 2;
  const headers = rows.length > 0 ? Object.keys(rows[0]) : [];
  const columnWidth = headers.length > 0 ? contentWidth / headers.length : contentWidth;
  const lineHeight = 9;
  let y = margin;

  const addPageHeader = () => {
    document.setFont("helvetica", "bold");
    document.setFontSize(15);
    document.setTextColor(7, 18, 13);
    document.text("LeadsStacks POS", margin, y);
    y += 18;
    document.setFontSize(12);
    document.text(title, margin, y);
    y += 15;
    document.setFont("helvetica", "normal");
    document.setFontSize(8);
    document.setTextColor(96, 118, 107);
    document.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
    y += 16;
  };

  const addSummary = () => {
    const entries = Object.entries(summary);
    if (entries.length === 0) return;
    document.setFontSize(8);
    document.setTextColor(23, 51, 36);
    document.text(entries.map(([label, value]) => `${label}: ${printable(value)}`).join("   |   "), margin, y);
    y += 18;
  };

  const addTableHeader = () => {
    document.setFillColor(14, 36, 24);
    document.rect(margin, y, contentWidth, 20, "F");
    document.setFont("helvetica", "bold");
    document.setFontSize(7);
    document.setTextColor(246, 255, 248);
    headers.forEach((header, index) => document.text(document.splitTextToSize(header, columnWidth - 8), margin + index * columnWidth + 4, y + 12));
    y += 20;
  };

  addPageHeader();
  addSummary();
  addTableHeader();

  rows.forEach((row, rowIndex) => {
    const cells = headers.map((header) => document.splitTextToSize(printable(row[header]), columnWidth - 8));
    const rowHeight = Math.max(18, ...cells.map((cell) => cell.length * lineHeight + 8));

    if (y + rowHeight > pageHeight - 34) {
      document.addPage();
      y = margin;
      addPageHeader();
      addTableHeader();
    }

    if (rowIndex % 2 === 0) {
      document.setFillColor(245, 250, 246);
      document.rect(margin, y, contentWidth, rowHeight, "F");
    }

    document.setFont("helvetica", "normal");
    document.setFontSize(7);
    document.setTextColor(23, 51, 36);
    cells.forEach((cell, index) => document.text(cell, margin + index * columnWidth + 4, y + 12));
    y += rowHeight;
  });

  const pages = document.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    document.setPage(page);
    document.setFont("helvetica", "normal");
    document.setFontSize(7);
    document.setTextColor(96, 118, 107);
    document.text("Generated by LeadsStacks POS", margin, pageHeight - 16);
    document.text(`Page ${page} of ${pages}`, pageWidth - margin, pageHeight - 16, { align: "right" });
  }

  document.save(normalizeFilename(filename, ".pdf"));
}
