export type Product = {
  id: number;
  emoji: string;
  tone: string;
  name: string;
  code: string;
  category: string;
  warehouse: string;
  unit: string;
  purchasePrice: number;
  salePrice: number;
  stock: number;
  rack: string;
  shelf: string;
};

export const products: Product[] = [
  {
    id: 1,
    emoji: "🧴",
    tone: "bg-pink-50",
    name: "Nivea Cocoa Body Lotion 400ml",
    code: "COS-0018",
    category: "Cosmetics",
    warehouse: "Main Store",
    unit: "Bottle",
    purchasePrice: 680,
    salePrice: 890,
    stock: 32,
    rack: "C-02",
    shelf: "S-03",
  },
  {
    id: 2,
    emoji: "🍚",
    tone: "bg-amber-50",
    name: "Pishori Rice Premium 5kg",
    code: "SUP-0042",
    category: "Supermarket",
    warehouse: "Main Store",
    unit: "Bag",
    purchasePrice: 1120,
    salePrice: 1450,
    stock: 18,
    rack: "G-01",
    shelf: "S-01",
  },
  {
    id: 3,
    emoji: "🛢️",
    tone: "bg-yellow-50",
    name: "Shell Helix HX5 Engine Oil 4L",
    code: "AUT-0021",
    category: "Auto Spares",
    warehouse: "Industrial Area",
    unit: "Can",
    purchasePrice: 2980,
    salePrice: 3650,
    stock: 9,
    rack: "A-05",
    shelf: "S-02",
  },
  {
    id: 4,
    emoji: "🔨",
    tone: "bg-slate-100",
    name: "Claw Hammer Heavy Duty 16oz",
    code: "HDW-0064",
    category: "Hardware",
    warehouse: "Industrial Area",
    unit: "Piece",
    purchasePrice: 520,
    salePrice: 750,
    stock: 24,
    rack: "H-03",
    shelf: "S-04",
  },
  {
    id: 5,
    emoji: "🍗",
    tone: "bg-orange-50",
    name: "Chicken Breast Fillet 1kg",
    code: "RST-0011",
    category: "Restaurant",
    warehouse: "Kitchen Store",
    unit: "Kg",
    purchasePrice: 560,
    salePrice: 850,
    stock: 14,
    rack: "F-02",
    shelf: "Freezer",
  },
  {
    id: 6,
    emoji: "💄",
    tone: "bg-rose-50",
    name: "Matte Lipstick Ruby Red",
    code: "COS-0071",
    category: "Cosmetics",
    warehouse: "Westlands",
    unit: "Piece",
    purchasePrice: 340,
    salePrice: 650,
    stock: 6,
    rack: "C-07",
    shelf: "S-02",
  },
  {
    id: 7,
    emoji: "🥛",
    tone: "bg-cyan-50",
    name: "Fresh Whole Milk 500ml",
    code: "SUP-0103",
    category: "Supermarket",
    warehouse: "Main Store",
    unit: "Packet",
    purchasePrice: 49,
    salePrice: 65,
    stock: 84,
    rack: "D-01",
    shelf: "Chiller",
  },
  {
    id: 8,
    emoji: "🔩",
    tone: "bg-zinc-100",
    name: "Galvanized Roofing Nails 1kg",
    code: "HDW-0097",
    category: "Hardware",
    warehouse: "Industrial Area",
    unit: "Packet",
    purchasePrice: 215,
    salePrice: 320,
    stock: 47,
    rack: "H-08",
    shelf: "S-01",
  },
  {
    id: 9,
    emoji: "🚘",
    tone: "bg-blue-50",
    name: "Brake Pads Toyota Axio Front",
    code: "AUT-0085",
    category: "Auto Spares",
    warehouse: "Industrial Area",
    unit: "Set",
    purchasePrice: 1650,
    salePrice: 2400,
    stock: 4,
    rack: "A-02",
    shelf: "S-05",
  },
  {
    id: 10,
    emoji: "🥤",
    tone: "bg-lime-50",
    name: "Passion Juice Fresh 500ml",
    code: "RST-0044",
    category: "Restaurant",
    warehouse: "Kitchen Store",
    unit: "Bottle",
    purchasePrice: 95,
    salePrice: 180,
    stock: 21,
    rack: "B-02",
    shelf: "Chiller",
  },
];

export const recentActivity = [
  { action: "New sale completed", detail: "Invoice #INV-2841 · Main Store", time: "8 min ago", type: "sale" },
  { action: "Low stock alert", detail: "Brake Pads Toyota Axio Front", time: "21 min ago", type: "alert" },
  { action: "M-Pesa payment received", detail: "KES 4,850 · QHG7R2K9", time: "44 min ago", type: "payment" },
  { action: "Stock transfer approved", detail: "Industrial Area → Westlands", time: "1 hr ago", type: "transfer" },
  { action: "New customer added", detail: "Amani Beauty Studio", time: "2 hrs ago", type: "customer" },
];

export const lowStockItems = [
  { name: "Brake Pads Toyota Axio Front", stock: 4, warehouse: "Industrial Area" },
  { name: "Matte Lipstick Ruby Red", stock: 6, warehouse: "Westlands" },
  { name: "Shell Helix HX5 Engine Oil 4L", stock: 9, warehouse: "Industrial Area" },
  { name: "Takeaway Containers 750ml", stock: 10, warehouse: "Kitchen Store" },
];
