import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { articles, SITE_URL } from "@/lib/marketing/site";
import { FinalCta, PublicPage } from "@/components/marketing/blocks";
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return articles.map(article=>({slug:article.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const article=articles.find(a=>a.slug===slug);if(!article)return{};return{title:`${article.title} | LeadsStacks`,description:article.excerpt,alternates:{canonical:`/blog/${slug}`},openGraph:{title:article.title,description:article.excerpt,url:`${SITE_URL}/blog/${slug}`,type:"article"},twitter:{card:"summary_large_image"}}}
export default async function ArticlePage({params}:Props){const {slug}=await params;const article=articles.find(a=>a.slug===slug);if(!article)notFound();const related=articles.filter(a=>a.slug!==article.slug).slice(0,3);const schema={"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.excerpt,datePublished:article.date,dateModified:article.date,author:{"@type":"Organization",name:"LeadsStacks"},publisher:{"@type":"Organization",name:"LeadsStacks",url:SITE_URL},mainEntityOfPage:`${SITE_URL}/blog/${article.slug}`};return <PublicPage><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><article><header className="bg-emerald-950 px-4 py-20 text-white sm:px-6"><div className="mx-auto max-w-3xl"><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">{article.category}</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">{article.title}</h1><p className="mt-5 text-lg leading-8 text-emerald-100/75">{article.excerpt}</p><p className="mt-6 text-sm text-emerald-100/60">By LeadsStacks · {new Date(article.date).toLocaleDateString("en-KE",{month:"long",day:"numeric",year:"numeric"})}</p></div></header><div className="mx-auto max-w-3xl px-4 py-16 sm:px-6"><div className="rounded-3xl bg-emerald-50 p-8 text-sm leading-7 text-slate-700">This guide is written for Kenyan and East African SME operators. It is practical information, not legal, accounting or tax advice.</div><div className="mt-10 space-y-7 text-[17px] leading-8 text-slate-700">{article.body.map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div><div className="mt-12 rounded-2xl bg-emerald-950 p-7 text-white"><h2 className="text-2xl font-black">Bring your business records together.</h2><p className="mt-3 text-emerald-100/75">See how LeadsStacks can help you run sales, stock, customers and reports from one connected platform.</p><Link href="/signup" className="mt-5 inline-block rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold">Start Free Trial</Link></div><section className="mt-14"><h2 className="text-2xl font-black text-emerald-950">Related guides</h2><div className="mt-5 grid gap-3">{related.map(a=><Link key={a.slug} href={`/blog/${a.slug}`} className="rounded-xl border border-emerald-950/10 p-4 text-sm font-bold text-emerald-950 hover:bg-emerald-50">{a.title} →</Link>)}</div></section></div></article><FinalCta/></PublicPage>}
